### ISSUE TITLE
Shiny plugin install should use name not slug for server callbacks

### ISSUE THREAD

**Issue by adamsilverstein** [obenland/shiny-updates#11]
Using the slug to request a plugin install, and sending back the slug to updated the UI can result in some edge case failures, for example where the slug contain special characters.  We recently switched the plugin upgrade callbacks on the plugin screen to use the plugin name which should be more reliable.

Lets switch the plugin install screen install callbacks to use the name as well.  

Related: https://core.trac.wordpress.org/ticket/35032

**Comment by obenland** [comment]
It looks like only `install-plugin` uses slugs, which makes sense because we don't have name for uninstalled plugins. Delete and update both use the plugin name. We'll just have to remember using it when we do activations, which I'm sure we will.
