### ISSUE TITLE
Table headers should never be empty

### ISSUE THREAD

**Issue by afercia** [obenland/shiny-updates#114]
In `update-core.php` the table header for the title column is empty.

**Comment by swissspidy** [comment]
Thanks for your input, @afercia!

----

What would describe the first column best? Just _Update_?

**Comment by afercia** [comment]
For the record, I guess text hidden with `screen-reader-text` would be fine.

**Comment by mapk** [comment]
I think if we remove the 'Available Updates' text from the top and just use that as the header like this:

![table-header](https://cloud.githubusercontent.com/assets/617986/15375646/fb3da270-1d04-11e6-8faf-dc4837a707d3.png)

**Comment by swissspidy** [comment]
Good idea! I'll change it like that and then we can test it.

**Comment by afercia** [comment]
Sorry, not to be picky but table headers should describe the type of data contained in the column cells. The "type" column is perfect in this regard. The last "Update All" column is not so great, will open a separate issue.

As per the first column: since this table uses `scope` attributes, screen readers will read out the title of each column while navigating through the table cells.
Say you're in the table row 2, column 3 then you navigate to the first column in the same row, screen readers will read out the column header and probably 'Available Updates' is not a great title for that column.
"Visually", it is a perfect title for the entire table, but not so great to give user a proper information. The singular form would be better: 'Available Update'.

<img width="1440" alt="screen shot 2016-05-19 at 09 38 53" src="https://cloud.githubusercontent.com/assets/1682452/15386086/1183c07c-1da6-11e6-815d-1b71c710ac30.png">

About the headings:
> Having two headers... one that says "WordPress Updates" and another below it that says "Available Updates" seems redundant.
Okay if in the page there's just one block of main content. But if you're going to split the core updates in a separate table, then two `h2` would be required for the two content sections.

**Comment by swissspidy** [comment]
Leaving this closed in favour of #118.
