### ISSUE TITLE
Don't show 'Update' button when there are no updates needed

### ISSUE THREAD

**Issue by mapk** [obenland/shiny-updates#115]
Right now the update-core.php page shows an 'Update' button next to both the Core row and the Translations row even though I don't have any updates pending.

![screen shot 2016-05-18 at 2 03 34 pm](https://cloud.githubusercontent.com/assets/617986/15375314/3a5b65ac-1d03-11e6-8ea2-7ce841c3e6bb.png)

These should probably be disabled, or hidden completely. I'd even suggest hiding the 'Update all' blue buttons as well if there are no updates.

**Comment by swissspidy** [comment]
Hmm interesting, haven't had problems with the translations row. On a trunk install not running shiny updates, the update button for core is always shown. Will test more using 4.5.2 though.

**Comment by swissspidy** [comment]
So in `prepare_items()` there's an `! empty( $translations )` check for the translations, for the row content there's a `! ! $item['data']` check. Since it's an array both times, I wonder why it doesn't work. 🤔

**Comment by mapk** [comment]
How do I know if my WordPress is on trunk? And if I'm not, how do I get it on trunk?

**Comment by swissspidy** [comment]
@mapk You can use the [Beta Tester](https://wordpress.org/plugins/wordpress-beta-tester/) plugin to upgrade to nightlies and beta releases.

After that, there will be a notice like "You are using a development version of WordPress. […]" in the list table indicating that you're running trunk.
