### ISSUE TITLE
Separate JavaScript - load code specific to pages only on those pages

### ISSUE THREAD

**Issue by adamsilverstein** [obenland/shiny-updates#12]
As we spread shiny updates from plugins.php to now include plugin-new.php, theme-install.php and update-core.php, we should carefully extract functionality for each page into its own file, plus a common file that would be included on all pages. 

We already have a start with `shiny-theme-updates.js`, I'm opening this issue to remind us to complete the process.

**Comment by obenland** [comment]
Do you really think that is necessary? We should try to abstract and reuse as much as possible obviously. How much of a size difference are we talking about here?

**Comment by adamsilverstein** [comment]
main reason i wanted to consider this is keeping the code more organized (also, the main update file is getting pretty long - maybe I can add some organization there).  I think just having one file for plugins and one for themes is enough for now, its not much code at all size wise.
