### ISSUE TITLE
Improve confirmation dialog on plugin deletion

### ISSUE THREAD

**Issue by swissspidy** [obenland/shiny-updates#127]
This ticket is about improving this confirmation dialog as a whole.

Right now, shiny plugin deletion seems like a great way for users to shoot themselves in the foot. Why?

Currently, when trying to delete a plugin, WordPress shows a clear warning if you really want to uninstall a plugin:

<img width="411" alt="screen shot 2016-05-20 at 18 18 27" src="https://cloud.githubusercontent.com/assets/841956/15434524/8c029d7a-1eb7-11e6-8438-9ca85ca28324.png">

If the plugin has an uninstall routine, the warning changes to indicate potential data loss:

<img width="540" alt="screen shot 2016-05-20 at 18 18 48" src="https://cloud.githubusercontent.com/assets/841956/15434535/97fca08a-1eb7-11e6-828e-fa0ed689ff77.png">

Additionally, there's an interesting [Trac ticket](https://core.trac.wordpress.org/ticket/20578) about adding a new option to this: Deleting without data loss.

<img width="425" alt="rkkb2w_zbk" src="https://cloud.githubusercontent.com/assets/841956/15434676/525b45c6-1eb8-11e6-942b-8c17e2b3ccb5.png">

As you can see, the whole process is more safe guarded to prevent the users from doing bad decisions. Even if this ticket is not (yet) in core, shiny plugin deletions already feels like a step backward:

<img width="528" alt="screen shot 2016-05-20 at 18 33 45" src="https://cloud.githubusercontent.com/assets/841956/15434871/700c3b6a-1eb9-11e6-83fc-2e7857c77a60.png">

Poor wording, no warning about the consequences.

Note that there's no such  warning at all when doing bulk deletion, as pointed out in #124.

So, what can we do? I see a few possibilities:

1. Implement our own modal dialog containing the confirmation buttons
1. Improve the wording and change the text if the plugin has an uninstall routine, just like core does.
1. Remove shiny plugin deletion for now and implement this in a future release
1. Do 2. with keeping the core ticket in mind, which will likely force us to do 1.
1. Anything else?

**Comment by swissspidy** [comment]
Interesting kinda related core ticket about adding a warning for bulk deleting media items: https://core.trac.wordpress.org/ticket/28235

**Comment by mapk** [comment]
Getting people to confirm before going down this road is the better decision.

Creating a dialog box that contains this info seems to be the solution.

**Comment by swissspidy** [comment]
As per yesterday's meeting, we need to:

1. Show a `windiw.confirm()` dialog on bulk deletion.
2. Indicate whether data will be deleted or not in the dialog.

**Comment by sourcerer-mike** [comment]
Just for research even when this is no longer the goal ;)
Using a thickbox is possible and easy aside these changes:

- ... hide the buttons via URL-Query like `&button=0`
- ... the buttons need to be placed around the iframe in the thickbox, so that the thickbox can be closed via "No, return me to the plugins."
- ... removing the adminbar in the dialog.

![screen 2016-06-01 10 38 06](https://cloud.githubusercontent.com/assets/2559177/15703455/9fc71fde-27e5-11e6-8c39-c8f334c3c181.png)
