### ISSUE TITLE
Taking a look at this plugin....

### ISSUE THREAD

**Issue by paaljoachim** [obenland/shiny-updates#13]
Hey

What about taking a look at this plugin:
https://wordpress.org/plugins/cleaner-plugin-installer/

**Comment by adamsilverstein** [comment]
@paaljoachim 

I looked briefly and thats a far-reaching plugin. Are there any specific features in this plugin that think are worth considering for shiny updates?

**Comment by paaljoachim** [comment]
I am thinking we can rethink how we install a plugin.
Search is a very important part in how we in general find our plugins. 

The default install plugin page:
![screen shot 2015-12-28 at 8 24 08 pm](https://cloud.githubusercontent.com/assets/5323259/12024104/0b0aa622-ada1-11e5-8889-c880ea5b120b.png)


Cleaner plugin installer: enhances the plugin install process.
![screen shot 2015-12-28 at 8 22 53 pm](https://cloud.githubusercontent.com/assets/5323259/12024118/2d499ed2-ada1-11e5-93b5-83177bdea77d.png)
Focus on search by Keyword, Tag or Author.

Here one can switch over to Topics, Collections (an enhanced Favorites which could save multiple favorite plugin groups/collections), Newest, Popular and Favorites.

I would suggest to:
- Add a better search by having a drop down selecting to search by Keyword, tag or author.
- Having a newest plugins tab.
- Having a bulk install of favorites.

**Comment by obenland** [comment]
I think a drag/drop plugin/theme uploader would be nice.

**Comment by adamsilverstein** [comment]
+1 would be great for builk upload and activate flow

**Comment by MichaelArestad** [comment]
Can we close this issue? It seems like we have a good idea of which ideas to take from this plugin.

**Comment by adamsilverstein** [comment]
Sure, closing. @paaljoachim thanks for raising the suggestions here, we will continue to discuss these as the project progresses.

**Comment by paaljoachim** [comment]
Glad to help out!
Btw I added onto the trac issue in regards to a better search. https://meta.trac.wordpress.org/ticket/1278
As searching for downloads/active installs and rating would also be very beneficial for most people.
