### ISSUE TITLE
update-core.php responsive love needed

### ISSUE THREAD

**Issue by afragen** [obenland/shiny-updates#130]
I was testing on my iPad and found an issue one the update-core.php page. The images are for a plugin but I assume the same problem exists for all. 

![image](https://cloud.githubusercontent.com/assets/1296790/15445755/f4071e34-1eba-11e6-9260-508db6000099.png)
![image](https://cloud.githubusercontent.com/assets/1296790/15445756/f426ccac-1eba-11e6-8638-7340c39ccaee.png)

**Comment by swissspidy** [comment]
Thanks for your feedback! Absolutely hadn't looked at it on smaller screens yet because we were still iterating on the overall layout. Will give the responsiveness some love though.

Note also that the "6 items" text isn't aligned properly and the update button exceeds the table.
