### ISSUE TITLE
Improve Update All functionality

### ISSUE THREAD

**Issue by swissspidy** [obenland/shiny-updates#132]
Right now, I see two problems with the 'Update All' functionality:

1. Without JS, the experience is less than ideal.  
 `su_update_all()` basically combines all other update handlers with the bleak screen of sadness. This means the 'Update All' progress consists of 4 iframes with a height of at least 750px each.  
 Ideally, this should be only 1 iframe. On the other hand, we could simply not show 'Update All' if JS is disabled.
2. 'Update All' basically goes through each item in the list to update it one by one, changing each item's 'Update' button along the way. This works quite well and allows us not having to do a synchronous batch updating in PHP (i.e. `su_update_all()` for Ajax).  
 But, perhaps we could improve the UI a bit. I was thinking of putting an overlay on the table so the user doesn't click on the other update buttons while 'Update All' is running and to indicate that it is indeed updating all the things.

**Comment by mapk** [comment]
The UI on WP version 4.5.2 shows an update icon that gets injected on each 'udpate' button signifying that something is about to happen.  If this isn't the case with Trunk, can we make it so?

![update-core](https://cloud.githubusercontent.com/assets/617986/15690402/308a3578-2738-11e6-9234-12b3315d0912.gif)

**Comment by afragen** [comment]
If this doesn't seem to happen any longer, can we make it happen again? Seems like a great indicator of something happening.

**Comment by swissspidy** [comment]
Honestly that feels more like a bug to me and I don't think it ever looked like this on trunk.

**Comment by afragen** [comment]
I was doing most all my testing in trunk.

**Comment by afragen** [comment]
I just had a thought about this but haven't tested anything.

For 2, why about using some JS to remove the href of all the buttons after the 'Update All' is clicked?

**Comment by swissspidy** [comment]
Removing the href attribute is pretty bad as it's not accessible. Instead, we usually disable buttons when an update is going on, which is also what I suggested in #179.

Perhaps this is enough here. Not sure.

**Comment by swissspidy** [comment]
-1 on adding the update icon to every button even though it's not yet actually running the update.

a) because it's inconsistent with how it works in all other areas
b) because in some parts we rely on the existence of the update icon to see if an update is already running or not. This change would break those scenarios.

Since the original issue #157 was closed and this here was merely a suggestion / idea, I'm closing this for now as it's _out of scope_. We can work on this on trac after an eventual merge, or in Shiny Updates V3 😉
