### ISSUE TITLE
Update trunk doesn't redirect to about page.

### ISSUE THREAD

**Issue by afragen** [obenland/shiny-updates#135]
In update-core.php, updating trunk does not redirect to the about page. I haven't tested update to release yet.

**Comment by afragen** [comment]
Actually, updating to release not shiny at all. :frowning:

**Comment by swissspidy** [comment]
Thanks for opening the issue. I will look into that as soon as possible!

> Actually, updating to release not shiny at all.

Sounds strange, but definitely worth testing this again properly.

**Comment by afragen** [comment]
> > Actually, updating to release not shiny at all.

> Sounds strange, but definitely worth testing this again properly.

Must have been user error. :stuck_out_tongue_closed_eyes: 
But 'Re-Install' button does not give feedback. It should at least change to 'Updating…'

**Comment by swissspidy** [comment]
Ah, gotcha, yeah re-install is a little bit different. Will test that as well.

**Comment by swissspidy** [comment]
Just implemented some changes to the core update functionality in 3abc739103b8351432d1dc0276ddd65d6902c338 and eda379f33dd27b7f423eaf394238414d9b17a28f. These fix the re-install button so it actually passes the `reinstall` flag via AJAX, something which was removed at some point (my bad).

During testing, the redirect to the about page worked flawlessly. If it doesn't work for you, it would be great if you could share the Ajax response you get after a core update (using F12). For the core update response, it should include the redirect URL.

<img width="924" alt="screen shot 2016-05-23 at 13 09 50" src="https://cloud.githubusercontent.com/assets/841956/15469032/f3c8b17e-20e7-11e6-96ea-545636019142.png">
_An example AJAX response for WooCommerce_

**Comment by afragen** [comment]
All works great on latest update.
