### ISSUE TITLE
Plugin update doesn't install/update translations

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#138]
Steps to reproduce:

* Set language to German
* Update version of Akismet to 3.1.10
* Delete all existing translations for Akismet
* Go to update-core.php
* Click update button for Akismet

Expected: `WP_LANG_DIR/plugins/` contains aksimet-de_DE.po and  aksimet-de_DE.mo.
Actual: aksimet-de_DE.po and  aksimet-de_DE.mo is missing.

**Comment by swissspidy** [comment]
Thanks for ruining my weekend by filing some bugs 😛

I wonder why this is not working.

`wpsu_ajax_update_plugin()` calls `Plugin_Upgrader::bulk_upgrade()`, which fires the `upgrader_process_complete` action, where the translation upgrader is hooked to. It's basically a copy of `wp_ajax_update_plugin()` after all.

**Comment by ocean90** [comment]
I just noticed that the existing shiny update in core doesn't work too. :(

**Comment by ocean90** [comment]
https://core.trac.wordpress.org/browser/trunk/src/wp-includes/update.php?marks=681,694,701,687#L680

The `upgrader_process_complete ` callbacks need to be moved out of the condition. I'll open a Trac ticket.

**Comment by ocean90** [comment]
https://core.trac.wordpress.org/ticket/36914

**Comment by swissspidy** [comment]
Awesome, thank you!
