### ISSUE TITLE
Update All doesn't update core when translations are included

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#139]
For some reasons a short "Update failed" flashes and the primary button stucks at "Updating…". And it seems only to happen if the list includes translations.

The XHR response for the `update-core` action is `0`.

Screencast:
![core](https://cloud.githubusercontent.com/assets/617637/15456045/e5f94d66-2064-11e6-98c8-db12f7a0e250.gif)

**Comment by swissspidy** [comment]
I briefly remember getting the `0` response during development once or twice.

Ps. The jumping table column is not cool. Will have to look at that too.
