### ISSUE TITLE
Prevent updating of already updated plugins on the plugin-install.php screen

### ISSUE THREAD

**Issue by afercia** [obenland/shiny-updates#145]
With Shiny Updates activated, I see this previously fixed issue happening again, see
https://core.trac.wordpress.org/ticket/35257

Basically, after the first successful update, you can still click on the "Updated!" button and you will see the green check mark spinning and finally get an update failed message.

**Comment by swissspidy** [comment]
Thanks for the report! Phew, I guess we can simply port this change to the plugin, not a big deal 😃

**Comment by afercia** [comment]
:)

<img width="650" alt="screen shot 2016-05-23 at 17 55 25" src="https://cloud.githubusercontent.com/assets/1682452/15486773/61747540-2148-11e6-8765-2592aca6e0e9.png">
