### ISSUE TITLE
Install from the Tools - Import screen

### ISSUE THREAD

**Issue by afercia** [obenland/shiny-updates#148]
Trying to install an Importer Plugin from the Tools > Import screen currently fails.
- click on an importer
- the plugin details modal opens
- when the modal content has finished loading, Chrome console displays an error `SyntaxError: Unexpected token o in JSON at position 1`
- clicking on the "Install Now" button in the modal does nothing

**Comment by swissspidy** [comment]
Hah, I honestly never tried using Shiny Updates on that screen. Never use the tools screen in general.

**Comment by afercia** [comment]
It came to my mind just because I was working on the Import screen :) By the way, after activation usually these importers redirect to a screen where users can immediately run the importer so they have their own peculiar workflow. Wondering if keeping the existing workflow would be the best thing.

**Comment by swissspidy** [comment]
I'll have a look at the workflow, but even if it would not be possible to add it, shiny _install_ is definitely something to consider for it. Redirect happens only after _activation_.

**Comment by swissspidy** [comment]
**Current flow without Shiny Updates**

1) Overview

<img width="1098" alt="screen shot 2016-05-29 at 17 23 45" src="https://cloud.githubusercontent.com/assets/841956/15634379/b7cd4a2e-25c2-11e6-973b-3d722cf46fb3.png">


2) Clicking on a plugin opens the modal

<img width="1092" alt="screen shot 2016-05-29 at 17 24 07" src="https://cloud.githubusercontent.com/assets/841956/15634381/c8746f92-25c2-11e6-8eec-ccfe018ba8cc.png">


3) Clicking on "Install Now" shows the bleak screen of sadness, with the link "Activate Plugin & Run Importer" at the end

<img width="738" alt="screen shot 2016-05-29 at 17 24 24" src="https://cloud.githubusercontent.com/assets/841956/15634382/d2165826-25c2-11e6-860b-4e135811f0b8.png">

4) Clicking on the activation link redirects to the import screen for that plugin.

<img width="706" alt="screen shot 2016-05-29 at 17 24 36" src="https://cloud.githubusercontent.com/assets/841956/15634403/0fe3695a-25c3-11e6-8946-496f61dbabaf.png">

**Comment by swissspidy** [comment]
With 353de3cd9d4618d2024b19bccea59b358c58d9cd (see #159), the shiny install now works, but there's no visual feedback for what's going on.

I suggest calling `wp.updates.installPlugin` with different success / error handlers (e.g. `wp.updates.installImporterSuccess`) on the import screen that does the following:

1. Add an admin notice on success / error
2. Show an activation link inside the notice
3. Change the plugin install link to an activation link
4. Activate the plugin in the background and redirect via JS on success
