### ISSUE TITLE
`Install Update Now` button in the plugin update details popup is not shiny

### ISSUE THREAD

**Issue by Nikschavan** [obenland/shiny-updates#153]
The `Install Update Now` still redirects to old updating page.

![](http://goo.gl/ZKCjiT)

I am not sure if this is in the current scope of the plugin though.

**Comment by swissspidy** [comment]
It is in the scope, because it should already be shiny when on the plugins management screen. It just happens to not work on the revamped update-core.php page, so I will look into that.

**Comment by Nikschavan** [comment]
I will be happy to PR with some initial guidance :)

**Comment by Nikschavan** [comment]
From WordPress [trac ticket](https://core.trac.wordpress.org/ticket/37126), Updates fail when installing from shiny details modal. [screenshot](https://cldup.com/57EOl9W2a0.png)
