### ISSUE TITLE
The 'core update' row is shown for an up to date install on multisite

### ISSUE THREAD

**Issue by Ipstenu** [obenland/shiny-updates#154]
![screen shot 2016-05-25 at 9 24 12 am](https://cloud.githubusercontent.com/assets/807903/15547866/9b4c0518-225a-11e6-81aa-d50fc852a1e3.png)

This doesn't actually tell me WHAT needs to happen. And in fact, it's wrong as I'm on 4.5.2 so there really is no "update" needed for core at the moment.

**Comment by swissspidy** [comment]
That's… weird. Thanks for pointing it out!

Of course that row shouldn't be shown since your already on the latest version. That's why there is no content inside. Otherwise it makes more sense.

So the actual bug is that the row is showing despite there being no actual update.
