### ISSUE TITLE
Remove "0" from toolbar when no updates are available

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#155]
The bubble in the menu gets removed and also the table view link, but not the 0 in toolbar:

<img width="157" alt="bildschirmfoto 2016-05-25 um 19 54 47" src="https://cloud.githubusercontent.com/assets/617637/15550649/bddea63c-22b2-11e6-9155-666d068d7994.png">

**Comment by swissspidy** [comment]
Shouldn't the whole toolbar item get removed when there's no update?
