### ISSUE TITLE
No default plugins installed

### ISSUE THREAD

**Issue by paaljoachim** [obenland/shiny-updates#16]
I would suggest having no default plugins installed.
As in remove Hallo Dolly and Akismet.

Just start out with a big search bar or if the user has an account at wordpress.org have favorites show up first as the user has already favorited plugins and it seems like the most logical place to start with.

**Comment by obenland** [comment]
I'm not sure what this is in reference to? The plugin install screen?

**Comment by paaljoachim** [comment]
Creating a new site one starts out with Hello Dolly and Akisment already in place in the installed plugins screen. This really should start out blank.

**Comment by obenland** [comment]
That is not really what this plugin is about. We're trying to make plugin and theme related flows more appealing to users.

**Comment by paaljoachim** [comment]
Ok. Gotcha.
