### ISSUE TITLE
Installing from modal on update-core.php

### ISSUE THREAD

**Issue by afragen** [obenland/shiny-updates#170]
From update-core.php if I select a 'View details' for an update and get a modal, Selecting the 'Install Update Now' button only closes the modal. No update occurs.

Shiny update does occur in modal from plugins.php

**Comment by swissspidy** [comment]
Huh, I thought I fixed that in bd81e51322e4182417d249f7be770c3085d052b1. Are you using the latest version of the plugin? Can you confirm the line in question of the JS file looks like the one in the commit?

**Comment by afragen** [comment]
Definitely using latest version of plugin. Even after today's update it still has the same issue.

From the Javascript console
> shiny-updates.js?ver=4.6-alpha-37590:982 Uncaught TypeError: Cannot read property 'find' of undefined

**Comment by swissspidy** [comment]
Ah, gotcha. This error would be fixed in #164, see especially f33852ec112953c89893b8ea81881135f88cb28b touching the line in question (982).

Would be great if you could give that branch a spin and see if it works.

**Comment by afragen** [comment]
OK, I switched to the branch `fixes/filesystem-credentials-dialog` and now I get updates from the modal but not shiny. Updates from modal in plugins.php still shiny.

**Comment by obenland** [comment]
@afragen Could you update to latest master and test again? It should have been fixed in #174.

**Comment by afragen** [comment]
So I saw you merged #174, I switched back to master in GitHub and now I get a shiny update from the update-core.php modal, but the spinner doesn't stop. There's no indication of completion.

JS console error.
> shiny-updates.js?ver=4.6-alpha-37597:369 Uncaught TypeError: Cannot read property 'attr' of undefined

Repeatable after several attempts.

**Comment by swissspidy** [comment]
Thanks for pointing this out!

Looks like `$updateMessage` isn't set all the time in `wp.updates.updateSuccess` and I missed it.

**Comment by afragen** [comment]
Great! Let me know which branch to test with next.
