### ISSUE TITLE
Missing translators comments

### ISSUE THREAD

**Issue by swissspidy** [obenland/shiny-updates#172]
In some parts of the plugin, like the JS templates, there are some missing translators comments.

**Comment by swissspidy** [comment]
@ocean90 How would you add translators comments inside the JS templates?

For example, `su_theme_templates()` contains this line:

```
<div class="theme-author"><?php printf( __( 'By %s' ), '{{{ data.author }}}' ); ?></div>
```

I think we should add a note about `%s` being the theme author's name.

**Comment by ocean90** [comment]
@swissspidy  Yes, it's still PHP.
```
<div class="theme-author"><?php
/* translators: %s: theme author */
printf( __( 'By %s' ), '{{{ data.author }}}' );
?></div>
```

**Comment by swissspidy** [comment]
I know it's PHP 😛

Was thinking if 

```
<?php /* translators: … */ ?>
<div>…</div>
```

would work too, but I guess no. Will implement it like you suggested. Thanks!
