### ISSUE TITLE
Dismiss core updates

### ISSUE THREAD

**Issue by swissspidy** [obenland/shiny-updates#176]
Currently in WordPress, available core updates can be dismissed by clicking on a button on `update-core.php`. See `do_dismiss_core_update()` and `do_undismiss_core_update()` for the implementation.

Should we deprecate this functionality with the introduction of Shiny Updates or add this somewhere? Ideas?

**Comment by swissspidy** [comment]
So this was discussed in yesterday's dev chat and the consensus was to add support for this.

@ocean90 shared some screenshots of how this feature currently looks like:

<img width="1117" alt="4 5 1-to-4 5 2" src="https://cloud.githubusercontent.com/assets/841956/15743487/21e8eaa2-28c6-11e6-8396-88a4484d5b1b.png">
<img width="1103" alt="4 5 1-to-4 5 2-de-hidden" src="https://cloud.githubusercontent.com/assets/841956/15743488/21e92de6-28c6-11e6-97f3-8f5bb05a17bc.png">
<img width="1012" alt="4 5 1-to-4 5 2-de-hidden-bring-back" src="https://cloud.githubusercontent.com/assets/841956/15743486/21e6e626-28c6-11e6-8d05-e49bee18206a.png">

Apparently the purpose of this functionality was discussed [in a core ticket](https://core.trac.wordpress.org/ticket/36998) years ago.

If I were to reproduce the above scenario on a local site, I think it would look quite weird with Shiny Updates enabled, because we don't really account for that scenario.

How should this look like in Shiny Updates? It would be a bummer to not ship `update-core.php` changes because of this.

Pinging @mapk for a design suggestion.

**Comment by obenland** [comment]
How about a Hide this update button that looks like a link in the main column that transfers the row to a small row only showing a Show hidden updates button that looks like a link?

**Comment by mapk** [comment]
Something like this?

"Hide this update" link:
![hide this update](https://cloud.githubusercontent.com/assets/617986/15752597/b42b5878-28a3-11e6-911f-f8d11bea99b6.png)

When update is hidden:
![hidden update](https://cloud.githubusercontent.com/assets/617986/15752613/c35ec44c-28a3-11e6-863d-5a85173a8d32.png)

**Comment by obenland** [comment]
Exactly. The hidden update row could even be more narrow, like when you mark a comment as spam.

**Comment by swissspidy** [comment]
That could work 👍 

Note that we we need to test this with the scenario when there are basically three updates (as per the screenshots):

* Install 4.5.2-de_DE
* Install 4.5.2-en_US
* Re-install 4.5.2

Only the first one should be dismissible.

**Comment by obenland** [comment]
we should be able to re-use most of the existing code for that no?

**Comment by swissspidy** [comment]
Yeah, we can copy most stuff. But since our updates table looks quite different and we do not simply loop over all available core updates, I think it needs some tweaks. Will happily dig into it.

**Comment by swissspidy** [comment]
#198 implements like 90%. What's not working yet is displaying the de_DE _and_ the en_US package of an available update. Currently only the first update is shown, in this case the localized one. See first screenshot in this thread.

@mapk @obenland Do we want to add another row for this other package? Or just another button in the table row? Or beneath the "Update" button?

**Comment by obenland** [comment]
That sounds like a question for @ocean90, I'm not sure what the preferred behavior is there

**Comment by mapk** [comment]
I think having two rows with the only difference being some minor text that reads "de_DE" or "en_US" would get rather confusing.  So initially I'm opting for adding just another button that specifies the locale within the row.

I'm not entirely sure I'm thinking through this correctly though... :)

**Comment by ocean90** [comment]
> Do we want to add another row for this other package?

If you only have one, where are you going to add the "Hide this update" link? / How would the other package come up? I think two rows are the way to go.

**Comment by swissspidy** [comment]
Having two rows does definitely make it easier. What happens when you click "Update All" though, which update should be installed? The localized one or en_US?

**Comment by ocean90** [comment]
Good question. My first screenshot shows a primary button for the localized one so let's use that for "Update All".
The update queue should also never contain more than one core update.
