### ISSUE TITLE
Confirmation dialog after plugin update

### ISSUE THREAD

**Issue by sourcerer-mike** [obenland/shiny-updates#177]
With shiny-updates disabled, the update of a plugin finishes and I can navigate to somewhere else.

With shiny-updates **enabled**, the update of a plugin finishes and when I navigate somewhere else, then I get a confirmation modal.

This occured in a new WP 4.4.3 with Akismet update.
I set back the Akismet version in the comment to test it several times.

**Comment by swissspidy** [comment]
Hey there

Thanks for your report! I couldn't reproduce this on `wp-admin/plugins.php`. On which page is this happening for you?

**Comment by sourcerer-mike** [comment]
During the chat yesterday I was able to do it. Now I checked again in a clean install with WP 4.4.3 and the latest. It works.

Dunno what went wrong yesterday. Sorry.
