### ISSUE TITLE
Re-install on update-core.php

### ISSUE THREAD

**Issue by afragen** [obenland/shiny-updates#178]
When using the "Re-install" button to switch from trunk to release version. There is no spinner in the button and the re-install is not shiny.

**Comment by swissspidy** [comment]
Hmm, maybe this broke after the latest refactoring today, because it worked after #135. Will have a look.

**Comment by swissspidy** [comment]
I assume changing the click handler from `$( '#wp-updates-table' ).on( 'click', '.update-link', function( event ) {` to something like `$( '.update-core-php' ).on( 'click', '.update-link', function( event ) {` should already work.
