### ISSUE TITLE
Clicking the update button more than once should not end in error messages

### ISSUE THREAD

**Issue by sourcerer-mike** [obenland/shiny-updates#179]
Under "Updates" you can click the update button while it is updating.
Those clicks enqueue and end in error messages.

![screen 2016-05-31 22 27 08](https://cloud.githubusercontent.com/assets/2559177/15689452/567b2d22-277f-11e6-97a3-47ffc4c333be.png)

The fun part is, that clicking all possible updates several times makes the check-mark spin in every update that is done.

**Comment by swissspidy** [comment]
Thanks for pointing this out! We should add the `disabled` attribute to the button while it's updating.

From a quick glance it looks like something in this regard is in the code, but perhaps not working.

**Comment by swissspidy** [comment]
Previously: #145.
