### ISSUE TITLE
Show "abort update" button 

### ISSUE THREAD

**Issue by sourcerer-mike** [obenland/shiny-updates#180]
In "update" screen you can update WP, Plugins and Themes.
Please add an "Abort"-Button while something is updateting as long as it is possible.

Might have an invisible countdown of 2-3 seconds.
Might grey out when it is no longer possible.

**Comment by swissspidy** [comment]
That would only make sense for the "Update All" button. It could change to a "Cancel" button which simply clears the queue. If it works and is easy to implement and is a benefit for users — why not?

**Comment by swissspidy** [comment]
Note that such functionality needs to make it clear that it doesn't really _abort_ a currently running update, but _cancel_ any pending updates.

**Comment by sourcerer-mike** [comment]
Oh okay. The intention was to cancel the current running update. But if this is impossible I leave it open for the "Update all" action.

**Comment by obenland** [comment]
Given code freeze on Friday, this feels more like an enhancement for it once it's in Core.

**Comment by swissspidy** [comment]
Yeah, cancelling the currently running update (and rollback to previous state) is way out of scope for Shiny Updates (and probably not possible at all) and would need to be discussed on WordPress Trac. Related ticket: [#31744](https://core.trac.wordpress.org/ticket/31744)

A button to clear the update queue hasn't been on our roadmap and I don't want to rush something like that in right before feature freeze.
