### ISSUE TITLE
No View details link for themes, Version 2-20160601

### ISSUE THREAD

**Issue by joyously** [obenland/shiny-updates#187]
Under Dashboard -> Updates, each plugin has a View details link, but the themes have no links, unlike under Appearance -> Themes -> theme detail.
I know it's not there in core either, but it should be.

**Comment by afragen** [comment]
This would be a core change. Probably best to put a trac ticket in there.

**Comment by swissspidy** [comment]
@afragen Not necessarily a core change as Dashboard -> Updates is totally different in Shiny Updates.

@joyously is right, "View details" link is shown under Appearance -> Themes and it seems legit to me to include it in the updates table as well for the sake of parity.

**Comment by swissspidy** [comment]
Not adding this for now for the reasons discussed in #196.
