### ISSUE TITLE
Design of Dashboard -> Updates page, Version 2-20160601

### ISSUE THREAD

**Issue by joyously** [obenland/shiny-updates#188]
I can't find anything on the Dashboard -> Updates page that is an improvement over core 4.5.2.
The plugin splits the core update information to top and bottom of the page, making it more difficult to determine core status. It also removes the informational message about future security updates being applied automatically, which is a bit unnerving.
It makes more sense the current core way to have checkboxes and one Update button than to have a myriad of Update buttons. It the user wants to do them individually, he would go to the Plugins page or the Themes page.
Having a column for thumbnails, with no thumbnails, is weird looking.
Mixing the themes and plugins in one table is a bad idea for UI. It is less obvious what is what.

All in all, this page of the plugin functionality is a big step backward and I hope it does not become core code.

**Comment by obenland** [comment]
Thank you for your feedback! I'm sorry you feel this way about the `update-core` page, we've had positive feedback about quite a few of the things you mention in our user tests. At this point we probably won't make any major changes to the UI there, but I'd like to share some of the thoughts behind our decisions.

> It […] removes the informational message about future security updates being applied automatically

The message is being displayed based on whether the installation supports ssl or not, that has not changed from current Core.

> It makes more sense the current core way to have checkboxes and one Update button than to have a myriad of Update buttons.

We've simplified it even more, offering Update All buttons that update everything, no matter if it's a plugin or a theme. With not using checkboxes we've actually reduced the amount of clicks a user has to make to update selected items. They all get queued right away and it doesn't need to wait for a final push of a button to get started.

> Having a column for thumbnails, with no thumbnails, is weird looking.

I absolutely agree. We're still waiting for an API change on the WordPress.org side that would send those thumbnails along with the update response. It's only temporary!

> Mixing the themes and plugins in one table is a bad idea for UI.

We've tried to mitigate that with the `type` column. In the end we felt stronger about consolidating three tables and removing that visual clutter.

Please feel free to add any additional feedback to #116, where we've been discussing the design of that page.

**Comment by joyously** [comment]
> The message is being displayed based on whether the installation supports ssl or not, that has not changed from current Core.

Perhaps so, but in my test the only thing that changed was whether Shiny Updates was installed or not. The message should show with the plugin, if it shows without it. 
It is very confusing to have the core update info split up.


> We've simplified it even more, offering Update All buttons...

Perhaps it is more simple, but you didn't address the rest of my statement:
>  It the user wants to do them individually, he would go to the Plugins page or the Themes page.

The point is that the checkboxes are a better interface, with precedent in the Bulk Actions of the plugins page.


> We've tried to mitigate that with the type column. In the end we felt stronger about consolidating three tables and removing that visual clutter.

What you call clutter is what I call organization. It is far better that less experienced users clearly know there is a mixture of themes and plugins than it is for you to meet some unproven design aesthetic.
