### ISSUE TITLE
not very shiny, Version 2-20160601

### ISSUE THREAD

**Issue by joyously** [obenland/shiny-updates#190]
I find it that with the plugin, the update notifications are more difficult to see than without the plugin for 2 out of 3 scenarios.
For an active plugin, the notification is more prominent the core way.
For inactive plugins, the notification is slightly more prominent the Shiny Updates way.
For themes, the notification is more prominent the core way.
Here is the plugin page the core way:
![plugins-without](https://cloud.githubusercontent.com/assets/7957680/15727811/979c4940-281e-11e6-8065-b8b4c3023ea2.jpg)

Here is the plugin page the Shiny Updates way:
![plugins-with](https://cloud.githubusercontent.com/assets/7957680/15727858/c66b1936-281e-11e6-8d74-fd375b2a08da.jpg)

Here is the theme page the core way:
![themes-without](https://cloud.githubusercontent.com/assets/7957680/15727880/de4c8864-281e-11e6-8f67-9defeccf14ce.jpg)

Here is the themes page the Shiny Updates way:
![themes-with](https://cloud.githubusercontent.com/assets/7957680/15727892/ea20099a-281e-11e6-97b8-35ba2ae1f793.jpg)

**Comment by mapk** [comment]
Thanks for these screenshots. Our goal with these notifications is to unify the design across the entire wp-admin. While some items may be less noticeable than they were before (ex. the Themes Dir), they're beginning to make the notification system feel more like a single unit.

That being said, we're still discussing ways in which we can improve some areas, and we appreciate your feedback.
