### ISSUE TITLE
Theme/Plugin Workflow Results

### ISSUE THREAD

**Issue by RachelRVasquez** [obenland/shiny-updates#192]
Hi there! I'm new to Shiny updates and giving it a try! Saw the note about testing in WP A11y and for workflow so giving it a go.

I've went through both workflows for Theme/Plugin tests specified here: https://wordpress.org/plugins/shiny-updates/

So far I only have minimal feedback/questions. 

1. For IE9, when installing a new theme, the "install now" button styles are kind of wonky.
2. I noticed the same spinner icon used in the plugin installs are also used on the themes to update. However the spinner icon next to "New Version Available. Update Now" for an outdated theme doesn't animate like the plugin version does. Is that intentional?\
3. When installing a new plugin, depending on the size of the plugin and internet connection, the spinner icon and the time it takes to install can feel like a long time. (E.g. BuddyPress, WooCommerce, sizable plugins like that) Perhaps having a percentage or some other visual in addition to the spinner can help inform users of how far along in the installation process they are without feeling like the page might have froze or the install has gone wrong.

I'd like to spend more time reviewing this - particularly for a11y things as well. Seems like a handy and cool plugin so far. Appreciate all the hard work. :-)

**Comment by obenland** [comment]
Thanks for your feedback @RachelRVasquez!

The IE issue seems to be something unrelated to Shiny Updates, if we have time we should fix that in core at some time. I opened a PR in #193 with a fix for the second item you mentioned. Unfortunately it is not trivial to offer real time updates about the current status of an ajax operation, so the spinner is currently the best we can do.
