### ISSUE TITLE
New issues with multisite not working in update-core.php

### ISSUE THREAD

**Issue by afragen** [obenland/shiny-updates#199]
In past 48 hours something no longer lets shiny updates work with multisite.

I can only update trunk, all other button clicks give the following error.

>updatePlugin — shiny-updates.js:325TypeError: undefined is not an object (evaluating '$message.attr')

Updating from single site install works fine.

**Comment by obenland** [comment]
Is this in `wp-admin/network/plugins.php`? Are you on the latest version? (in the latest version the `aysDelete` string reads "Are you sure you want to delete %s and its data?")

**Comment by swissspidy** [comment]
@obenland Per the issue's title it's on update-core.php 🙂

**Comment by swissspidy** [comment]
Can't reproduce this using the latest version on a multisite setup. Chances are high that some recent changes fixed this.

@afragen Please let us know about your findings. Thanks!

**Comment by afragen** [comment]
I just updated to latest version of Shiny Updates. In 2 different multisite test environments. Themes update but no spinner displayed, only check mark when finished. Plugins no update. Just an empty button click.

Error listed
> updatePlugin — shiny-updates.js:332TypeError: undefined is not an object (evaluating '$message.html')
> [Error] TypeError: undefined is not an object (evaluating '$message.attr')
	updatePlugin (shiny-updates.js:325)
	queueChecker (shiny-updates.js:1219)
	updateItem (shiny-updates.js:1096)
	(anonymous function) (shiny-updates.js:1846)
	dispatch (jquery.js:3:12450)
	handle (jquery.js:3:9179)

**Comment by afragen** [comment]
On a brand new vagrant multisite, with only Shiny Updates installed and active I decremented the version number of Hello Dolly and still an empty button click with the following error.

> updatePlugin — shiny-updates.js:332TypeError: undefined is not an object (evaluating '$message.html')
