### ISSUE TITLE
Some kind of notification when deleting a plugin

### ISSUE THREAD

**Issue by jonathanbossenger** [obenland/shiny-updates#202]
More of a request than an issue, installed plugin for the first time today to test.

When deleting a plugin I think it would be useful to show some kinda of indication that the plugin is being deleted. At the moment once clicking 'Ok' on the alert screen, nothing seems to happen for a few seconds, and then the plugin fades out.

The user has no way of knowing that deletion is actually in progress until the plugin is deleted.

**Comment by swissspidy** [comment]
> When deleting a plugin I think it would be useful to show some kinda of indication that the plugin is being deleted. At the moment once clicking 'Ok' on the alert screen, …

Isn't that confirmation dialog enough indication that the plugin is going to be deleted?

If not, we're going to have a hard time figuring out how to best add such an indication. Deletions are usually way faster than updates, so I'd think it would only be an issue for really slow sites.

**Comment by obenland** [comment]
I always like to compare it to deleting a comment, as it uses a similar visual feedback.

What makes it challenging is possibly having to handle an error message, so we can't really start to fade out right after the deletion was confirmed.

**Comment by swissspidy** [comment]
When deleting a comment the row is updated to show a text like "Comment by XY trashed. Undo".

So theoretically, we could add a similar row to the plugins list table when deleting a row.

**Comment by swissspidy** [comment]
CHeck out #252 guys. What do you think of that?
