### ISSUE TITLE
The new "bleak screen of sadness". User-journey dead end for failures.

### ISSUE THREAD

**Issue by rosswintle** [obenland/shiny-updates#203]
This screen isn’t a whole lot of fun: https://cloudup.com/co20RuhJPNG - it's my new "bleak screen of sadness".

The blue button at the top is lying (it says “Updated” when that’s clearly not the case) and there’s no indication about what to do next.

It really needs a “try again”, “reset”, “refresh status” or something.

I know that if I refresh this page then the statuses will reset, but I’m not normal; I've read the code for the previous shiny updates - I'm pretty weird. The flow for an ordinary user in this situation would be:

* Log in to Dashboard
* “Oh, I have updates”
* Navigate to Updates
* Click “Update All”
* Updates fail
* Argh. Panic. What do I do now?

We should really try to help users in a situation where something seemingly bad (failed updates) has happened.

Thoughts?

**Comment by obenland** [comment]
Update-core related changes were not approved for merge, closing.
