### ISSUE TITLE
FTP credentials form: Improve position of error notice on update-core.php

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#207]
Themes:
<img width="510" alt="ftp-themes" src="https://cloud.githubusercontent.com/assets/617637/15776427/c1ffa56e-2987-11e6-99be-518aaab4780c.png">

Core:
<img width="532" alt="ftp-core" src="https://cloud.githubusercontent.com/assets/617637/15776463/ec48772e-2987-11e6-85b7-0c5b70ad89ef.png">

**Comment by obenland** [comment]
Fixed in 9b1e4d92b08908958d27abeb125871992eb37300
