### ISSUE TITLE
"Future security updates will be applied automatically." is gone

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#209]
<img width="851" alt="" src="https://cloud.githubusercontent.com/assets/617637/15776746/3fdac7be-298a-11e6-8dde-24020d79af9b.png">

I think the message should be re-added to the update-core.php screen. Maybe in the "Need to re-install WordPress?" box?

**Comment by ocean90** [comment]
Ah, there it is:

<img width="1450" alt="" src="https://cloud.githubusercontent.com/assets/617637/15776845/1aaaaed6-298b-11e6-8867-45928d164060.png">

**Comment by swissspidy** [comment]
Already thought you wanted to troll me 😝

Glad you've found it. Would you still want to it somewhere else?

**Comment by swissspidy** [comment]
Assuming no.

Feel free to reopen otherwise.
