### ISSUE TITLE
Dismiss button is added twice to error notices

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#210]
<img width="1356" alt="dismiss" src="https://cloud.githubusercontent.com/assets/617637/15777731/d706efc6-2991-11e6-857d-f39473baa2f3.png">

The icon should be removed too since we don't use it for any other notices at this position. Maybe make `Update Failed:` bold?

**Comment by swissspidy** [comment]
Looks like Shiny Updates duplicates `makeNoticesDismissible()` with the `$document.on( 'wp-updates-notice-added wp-theme-update-error wp-theme-install-error', function() { … } )` click handler.

**Comment by obenland** [comment]
Core does it only for `wp-plugins-update-error` ([#](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/js/common.js#L402)), maybe we need to be more diligent with the events we're hooking it to?

I'd suggest the following:


	$( '.notice.is-dismissible:not(.has-button)' ).each( function() {
				var $notice = $( this ),
				    $button = $( '<button type="button" class="notice-dismiss"><span class="screen-reader-text"></span></button>' ),
				    /** @property {string} commonL10n.dismiss Dismiss message. */
				    btnText = commonL10n.dismiss || '';

				// Ensure plain text.
				$button.find( '.screen-reader-text' ).text( btnText );
				$button.on( 'click.wp-dismiss-notice', function( event ) {
					event.preventDefault();

					$notice.fadeTo( 100, 0, function() {
						$notice.slideUp( 100, function() {
							$notice.remove();
						} );
					} );
				} );

				$notice.addClass( 'has-button' ).append( $button );
			} );
		} );

But that really would need to be added to the callback in `common.js`.

**Comment by obenland** [comment]
Fixed in https://github.com/swissspidy/develop.wordpress/commit/116d06a541005cca3c92806b681b5bdc4d0e3929.
