### ISSUE TITLE
Change "Check Again" link to a link

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#212]
Follow-up to #209.

Discussion: https://wordpress.slack.com/archives/feature-shinyupdates/p1464952234001544

<img width="1452" alt="button- link" src="https://cloud.githubusercontent.com/assets/617637/15778025/ec5dff48-2993-11e6-856e-52aec6fd6318.png">

Doesn't need to be handled by the plugin but can/should be part of the core patch.

**Comment by swissspidy** [comment]
This is already fixed in [the patch I'm preparing](https://github.com/swissspidy/develop.wordpress/tree/shiny-updates).
