### ISSUE TITLE
Make the 'Updating' button ajaxify itself when done

### ISSUE THREAD

**Issue by Ipstenu** [obenland/shiny-updates#221]
I clicked 'update all' and it properly told me that my one plugin was updated, but the green (primary) top/bottom buttons got stuck on updating.

![screen shot 2016-06-03 at 9 39 51 am](https://cloud.githubusercontent.com/assets/807903/15786045/5077a9e0-296f-11e6-9bfa-964756db0674.png)

Shouldn't they too change to 'Updated!' ?

**Comment by obenland** [comment]
Hm, I can't reproduce that in either single or multisite. Would you mind re-installing Shiny Updates to get the latest version of today and see if it still happens?

**Comment by Ipstenu** [comment]
2-20160603 and it still happens :(

Multisite, network activated.

**Comment by swissspidy** [comment]
I cannot seem to reproduce this either. Is it still happening with the latest version? Any JS errors in the console?

**Comment by Ipstenu** [comment]
Okay, it ONLY happens on Multisite!

And it's interesting. On single, I get the spinning icon but on Multi I do not! The JS console is empty.

Single-site is just fine.

![screen shot 2016-06-05 at 5 jun - 4 05 01 pm](https://cloud.githubusercontent.com/assets/807903/15808843/48107df8-2b37-11e6-8366-53317270fc9c.png)

**Comment by swissspidy** [comment]
Thanks for your quick feedback!

A few observations:

1. In your first screenshot (running version 2-20160602)  the spinning icon was missing and the button text didn't change
2. In your second screenshot (running version 2-20160603) the button text did change.
3. There's no checkmark in the primary "Update All" button after the update is finished

The missing checkmark in the primary button is definitely a bug. #251 addresses this bug.

If the primary button's text is still not being updated in version 2-20160606, let us know.

**Comment by Ipstenu** [comment]
Looks like #251 also fixed this.

The second screenshot was of a single-site.

**Comment by swissspidy** [comment]
Awesome, great to hear! Thanks for testing!
