### ISSUE TITLE
Change Update button for translations when translations were updated async

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#227]
**Steps to reproduce:**

* Download https://downloads.wordpress.org/plugin/jetpack.4.0.2.zip and move "jetpack" into wp-content/plugins
* Switch site language to any language which has a language pack for Jetpack: https://translate.wordpress.org/projects/wp-plugins/jetpack/language-packs
* Go to update-core.php and update Jetpack
* Now try to update translations

Actual: It produces an "Update Failed" message.
Expected: Success.

**Screecast:**

![jetpack](https://cloud.githubusercontent.com/assets/617637/15792891/964f1338-29e0-11e6-968c-3bc54cba30b9.gif)
(I should have used another plugin as an example...)

**Fix**

1) Don't treat "The translation is up to date." as an error.
2) When successfully updating a theme/plugin, include the status of `wp_get_translation_updates()` in the Ajax response and change the label for the translations update button dynamically.

1) seems to be the easier fix. 2) would be nice. :)

**Comment by ocean90** [comment]
Note: If you're install is under version control use this snippet to enable async translation updates (`Language_Pack_Upgrader::async_upgrade()`).

```
add_filter( 'automatic_updates_is_vcs_checkout', function( $val, $context ) {
	if ( $context === WP_PLUGIN_DIR ) {
		return false;
	}

	return $val;
}, 10, 2 );
```

**Comment by obenland** [comment]
I think once we have 1) in place, we alleviate most of the pain that 2) would fix.
