### ISSUE TITLE
Update All cosmetic glitch

### ISSUE THREAD

**Issue by afragen** [obenland/shiny-updates#228]
When in trunk and there are 2 or more updates, selecting 'Update All' runs through the update but the update just before updating core continues to spin, as does the core update.

I was following the console and I noticed after the core update completed there was a quick flash of info showing the preceding plugin update. Odd that it showed after the core update when it clearly must have finished before. After core update completed About page redirect as usual.

This seems to happen in both single and multisite, but only in trunk. ( I think )

**Comment by obenland** [comment]
Yes, for some reason update-core runs as the second to last action in the queue. Trying to debug
