### ISSUE TITLE
Plugin icons missing in list of updates 

### ISSUE THREAD

**Issue by ms-studio** [obenland/shiny-updates#233]
Testing version 2-20160603 on WP 4.5.2, I notice that the plugin icons are missing – the space is there, but the icons don't show up.

<img width="998" alt="screen shot 2016-06-04 at 14 45 50" src="https://cloud.githubusercontent.com/assets/241637/15799636/188e5d36-2a63-11e6-9dc0-379f835c8041.png">

**Comment by ocean90** [comment]
See "Remaining Issues" section on https://make.wordpress.org/core/2016/06/02/proposal-more-shiny-updates/:
> Since the revamped updates table relies on plugin icons being returned by the Plugins API, the API <a href="https://meta.trac.wordpress.org/ticket/1714">needs to be changed</a> as part of the plugin directory update. The new directory will launch well before the 4.6 release, so that shouldn’t be a big deal. As a bonus, this change would also enable us to fix [#30186](https://core.trac.wordpress.org/ticket/30186).</p>

**Comment by swissspidy** [comment]
Yep, @ocean90 is right. We can add this in the future when a) Shiny Updates will hopefully already be part of core and b) when the API has been updated.
