### ISSUE TITLE
FTP credentials form: Disable key events by theme details modal

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#237]
Pressing the left/right arrow or ESC keys when the modal for the FTP credentials is open shouldn't change the theme details modal.

![theme-delete-arrow-keys](https://cloud.githubusercontent.com/assets/617637/15800258/9d3978fc-2a74-11e6-9ed5-2440f07b71a3.gif)

That's probably something which needs to be handled on merge.

**Comment by swissspidy** [comment]
Closing as it's fixed in the current version of the patch (see above commits).
