### ISSUE TITLE
Theme install: Remove focus class after successful install

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#238]
Looks like https://github.com/obenland/shiny-updates/blob/a89821bec87aaf8625bba37e37705258f48deae8/src/js/shiny-theme-updates.js#L32 was missed in #101.

**Comment by swissspidy** [comment]
Do you have a screenshot / GIF so I can see the error in action? Not sure what you mean.

**Comment by ocean90** [comment]
@swissspidy I have:


![focus](https://cloud.githubusercontent.com/assets/617637/15805053/b18d3678-2b1d-11e6-8aab-8527e2c88fe6.gif)

The `focus` class is added so the install button is visible during the installation.
