### ISSUE TITLE
plugins.php - Show plugins with available updates at the top and an update all button

### ISSUE THREAD

**Issue by j-falk** [obenland/shiny-updates#24]
*First, I love the initiative of continuing on the shiny updates path. Not really a developer but hope to be able to contribute in various ways, here's some thoughts.*

So if one purpose of this feature plugin is:
>As a WordPress administrator I want to easily update my plugins from plugins.php so that my WordPress is up-to-date and secure.

Then I think the default list view of plugins.php could be altered to even better highlight available updates and simplify the action of updating all available updates.

Right now plugins.php:
* Lists all installed plugins A-Z as default when coming to the page
* Highlight plugins with available updates with the update icon
* Provides the possibility to filter the list to only show plugins with vailable updates by clicking the "Updates Available" link above the list

Screenshot from existing plugins.php:
![plugins shiny updates wordpress](https://cloud.githubusercontent.com/assets/1665833/12044312/6d0bf8f0-ae8f-11e5-833d-e2a27f72cab3.png)

I think this default list view could be even better to further highlighting plugins with available updates and making it easier to update all available updates through:
* List plugins with available updates separately at the top so its super obvious which plusing that have available updates. This I think would be very useful especially wgen you have a long list of installed plugins.
* Provide a "Update All" button connected to this top part to easily initiate a bulk update

An example of a similar approach is how the Play Store in Android does this:
![updatescreen](https://cloud.githubusercontent.com/assets/1665833/12044466/1eed0990-ae92-11e5-9b81-44a33d70fe3c.jpg)

Then I also think the actual content of the plugins in the list could be further iterated to maybe become a bit cleaner and try to unify it a but with the card design in the installation process, but maybe that would be a separate issue.

**Comment by obenland** [comment]
We sort of already have that in the "Update Available" view, which lists only plugins that have, well, an update available. As I mentioned in #51, I'd like to avoid getting into refactoring the way the plugin list table works and leave that to a broader approach to all list tables.
