### ISSUE TITLE
Update All doesn't update core when JavaScript is disabled

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#244]
`su_update_all()` uses `do_core_upgrade()` which uses `find_core_update()`.

`find_core_update()` requires a version which `do_core_upgrade()` tries to set them via `$_POST['version']` and `$_POST['locale']`. But both values aren't set in the form: https://github.com/obenland/shiny-updates/blob/eeefec068f19f94ae348a58c95c852eb79b5b62b/src/class-shiny-updates-list-table.php#L572-L580.

For the record: I thought that Update All isn't available when JavaScript is disabled. I'm a bit worried about that `do_core_upgrade()` can run at the same time as plugin/themes updates since those are running in an iframe.

**Comment by swissspidy** [comment]
> For the record: I thought that Update All isn't available when JavaScript is disabled. I'm a bit worried about that `do_core_upgrade()` can run at the same time as plugin/themes updates since those are running in an iframe.

I suggested removing that in #132 and we talked about this once during the meeting, see [the archive](https://wordpress.slack.com/archives/feature-shinyupdates/p1464727460001301). The consensus is not very clear from there, but I'm +1 on removing "Update All"  when JS is disabled. Otherwise we'd need to install all updates in 1 iframe etc.

**Comment by swissspidy** [comment]
> Otherwise we'd need to install all updates in 1 iframe etc.

Happy to implement this if it's the better way. I can imagine the updates taking very long though.

**Comment by swissspidy** [comment]
Actually, there was a decision, see https://wordpress.slack.com/archives/feature-shinyupdates/p1464722052001197.

> > So `hide-if-no-js` for "Update All" or just leave as is?
> I think we should do that and remove `su_update_all()`. Not even deal with it and let them update individually

Will create a PR.
