### ISSUE TITLE
PHP Notice on update-core.php

### ISSUE THREAD

**Issue by afragen** [obenland/shiny-updates#248]
Using the latest `master` from GitHub I get the following PHP notices when viewing the update-core.php

> Notice	Undefined variable: update	2	/Users/afragen/Documents/Websites/wp-content/plugins/shiny-updates/src/functions.php:744	su_update_table()
 /Users/afragen/Documents/Websites/wp-content/plugins/shiny-updates/src/functions.php:744

> Trying to get property of non-object	2	/Users/afragen/Documents/Websites/wp-content/plugins/shiny-updates/src/functions.php:744	su_update_table()
 /Users/afragen/Documents/Websites/wp-content/plugins/shiny-updates/src/functions.php:744

It seems to happen as `$update` is not defined as I seem to be skipping over https://github.com/obenland/shiny-updates/blob/master/src/functions.php#L689

**Comment by afragen** [comment]
Adding this line back should fix, https://github.com/obenland/shiny-updates/commit/e476201da00985d77b73ec1a8d030414deb45d94#diff-84b928a9905378810b602c8a740b4cbaL744

**Comment by swissspidy** [comment]
This should be fixed by taking the data attributes out of the `wordpress-reinstall-card` div and into a separate `<div>`.
