### ISSUE TITLE
Activation under Multisite broken

### ISSUE THREAD

**Issue by jeffmcneill** [obenland/shiny-updates#254]
This Trac ticket should be reopened:

https://core.trac.wordpress.org/ticket/31327

I just experienced this behavior with the latest shiny updates 2-20160606 and the latest wordpress multisite. 4.5.2. 

- Go to network plugins
- Add plugin
- Install plugin
- Activate plugin
    - Expected behavior: network activation, and stay on Install Plugin page
    - Actual behavior: ejected to main site of the multisite plugin page, and main site has the plugin activated, network is not activated

**Comment by swissspidy** [comment]
That core ticket is quite unrelated as we do not auto-activate a plugin.

Essentially, what you say is that the plugin is activated only on the main site but not network-wide. Correct?

**Comment by swissspidy** [comment]
@obenland What do you think? We could change the button to "Network Activate" when in the network admin.

**Comment by ocean90** [comment]
@swissspidy That seems to be related to #259.

It should be "Network Activate" and `admin_url()` in `wp_ajax_install_plugin()` should be `network_admin_url()`.

**Comment by obenland** [comment]
Yes, what @ocean90 said

**Comment by swissspidy** [comment]
Re-opening for changing the button text as well.

**Comment by ocean90** [comment]
The same needs to be done for `su_plugin_install_actions()`.

**Comment by obenland** [comment]
Fixed in https://github.com/swissspidy/develop.wordpress/commit/f5c96e84ab33efb3d49a0b3e52f4fb6aeadd82d7.
