### ISSUE TITLE
Feature Request: Favorites Tab as default on Add Plugins page

### ISSUE THREAD

**Issue by jeffmcneill** [obenland/shiny-updates#257]
Favorites tab (with ability to save username) would be a fantastic default for the Add Plugins page. It is the only one relevant to most people most of the time (granted, they have to favorite some plugins).

**Comment by swissspidy** [comment]
Hey there

Thanks for your feedback so far. I'm closing this for the same reason as #256. Shiny Updates is not about improving the tabs on that screen. Feel free to create a trac ticket for that though! 

Keep in mind that only a tiny amount of WordPress users have a WordPress.org account, so showing that tab first might not be useful to the majority of users.
