### ISSUE TITLE
Disable plugin when feature is enabled in core

### ISSUE THREAD

**Issue by swissspidy** [obenland/shiny-updates#265]
Shiny Updates should not replace core stuff after merge, especially since the patch is now more advanced than the plugin.

How could we _disable_ the plugin properly in that case?

**Comment by adamsilverstein** [comment]
@swissspidy Can we check for one of the new functions we are adding to core in plugin load, and just not load the plugin code if present? I can work on this since you are tackling other bigger items.

**Comment by swissspidy** [comment]
@adamsilverstein Thanks for asking!

We were thinking about that as well. I think the only new functions we introduce are inside `wp-admin/includes/*` and are therefore not available when the plugin is loaded.

See [the Slack discussion](https://wordpress.slack.com/archives/feature-shinyupdates/p1465324790000239) about this. We might need to wait for a bump of `$wp_version` in order to change this in the plugin. After that it's quite easy.

Current patch progress: https://github.com/aaronjorbin/develop.wordpress/pull/5 — perhaps I'm missing something?

**Comment by chriscct7** [comment]
Can't you just version detect WordPress and disable the plugin if global $wp_version >= 4.6? Just wrap the load of the plugin in a version compare

**Comment by swissspidy** [comment]
That's the plan, yes. Needs to be a specific version number though. The one after merge.

**Comment by afragen** [comment]
If you use a number like `4.5.100` it will be disabled for those running trunk and after release you can change the number back to `4.6`.

Doing this will prevent those running trunk from having an active plugin after merge. Just a thought.
