### ISSUE TITLE
Disable "Update All" when all updates are completed

### ISSUE THREAD

**Issue by swissspidy** [obenland/shiny-updates#266]
Otherwise you can click on the button and it spins infinitely.

<img width="309" alt="screen shot 2016-06-07 at 11 27 28" src="https://cloud.githubusercontent.com/assets/841956/15853291/ab957856-2ca4-11e6-9d9f-fec41adeb0f3.png">

<img width="294" alt="screen shot 2016-06-07 at 11 27 53" src="https://cloud.githubusercontent.com/assets/841956/15853290/ab9511ae-2ca4-11e6-9545-5fcdace254d0.png">

**Comment by obenland** [comment]
Fixed in https://github.com/swissspidy/develop.wordpress/commit/8836b772ea0f4081e23acd3fedeb8a7e44f7f232.
