### ISSUE TITLE
Install translations when installing a plugin

### ISSUE THREAD

**Issue by swissspidy** [obenland/shiny-updates#267]
Without Shiny Updates, translations are automatically installed with the plugin:

<img width="684" alt="screen shot 2016-06-07 at 11 33 10" src="https://cloud.githubusercontent.com/assets/841956/15853660/4a10bde6-2ca6-11e6-9018-526460dd02a6.png">

With Shiny Updates, after installing and activating the same plugin it tells me to update translations:

<img width="1262" alt="screen shot 2016-06-07 at 11 51 44" src="https://cloud.githubusercontent.com/assets/841956/15853671/53d6d48c-2ca6-11e6-8da8-a827819401d2.png">

**Comment by ocean90** [comment]
Is that with current trunk?

**Comment by swissspidy** [comment]
The first screenshot is from a site running 4.5.2, the second is current trunk.

**Comment by ocean90** [comment]
@swissspidy Looks like trunk is under version control and 4.5.2 not?

Try this:
```php
add_filter( 'automatic_updates_is_vcs_checkout', function( $val, $context ) {
	if ( $context === WP_CONTENT_DIR || $context === WP_PLUGIN_DIR ) {
		return false;
	}

	return $val;
}, 10, 2 );
```

**Comment by swissspidy** [comment]
Ah yes that's the case. Not a bug then I guess :)
