### ISSUE TITLE
Search installed theme, delete it and get a blank screen

### ISSUE THREAD

**Issue by afercia** [obenland/shiny-updates#270]
Currently, **without** Shiny Updates:
1 go in themes.php
2 search for an installed theme, I've used "Intergalactic"
3 the search results will display 1 result ("Intergalactic"). Yay!
4 click to open the theme details modal
5 click "Delete"
6 the **page reloads** (so the search field will be empty) and you will be presented the list of installed themes

With Shiny Updates:
after 5) the page doesn't reload of course and the search field will still be filled with your search term ("Intergalactic", or part of t his string). So, after the theme gets deleted and the modal closes, the results is an empty page:

![shiny after delete theme](https://cloud.githubusercontent.com/assets/1682452/15868105/8afc4cd6-2ce6-11e6-9c83-c903a1f31a17.png)

Not a big deal I guess, the search field should just be emptied after a successful deletion

**Comment by swissspidy** [comment]
> Not a big deal I guess, the search field should just be emptied after a successful deletion

Sounds good to me.

Thanks for your report! 🍷

**Comment by obenland** [comment]
Thanks @afercia!

Fixed in https://github.com/swissspidy/develop.wordpress/commit/fafb31559be07b4ebfa72febf37bf2babaccca28.
