### ISSUE TITLE
Generic error handler

### ISSUE THREAD

**Issue by swissspidy** [obenland/shiny-updates#272]
Tracking ticket for https://wordpress.slack.com/archives/feature-shinyupdates/p1465419802000525.

Basically, if anything else than JSON is returned, we should somehow show that data. Currently (same goes for current core), nothing is output because the error handlers expect valid JSON.

**Comment by swissspidy** [comment]
We could solve this using a new internal `validateResponse` function that is called in all error and success handlers. If the response is not valid JSON, we should display the escaped response in an error notice and let all running updates fail (because we don't know which update the response was for and the error would be critical in this case).

**Comment by obenland** [comment]
Fixed in https://github.com/swissspidy/develop.wordpress/issues/5.
