### ISSUE TITLE
Remove Core when core is version controlled

### ISSUE THREAD

**Issue by kraftbj** [obenland/shiny-updates#275]
On a site that has WP under version control, could we remove core from the list of updates? Since there's not a way to select only some updates, the "Update All" functionality is problematic.

Could we disassociate Core from the Update All option when Core believes itself to be under a VCS?

**Comment by afragen** [comment]
Seems like a great opportunity for a filter. Example listed in PR

**Comment by ocean90** [comment]
Core ticket: https://core.trac.wordpress.org/ticket/35587

**Comment by swissspidy** [comment]
That problem hasn't come up during development of Shiny Updates, but I have seen the core ticket before.

I'm a bit concerned about putting something big like this in at this point.

By the way, in the language upgrader I found this piece of code:

```php
/*
 * Avoid messing with VCS installs, at least for now.
 * Noted: this is not the ideal way to accomplish this.
 */
$check_vcs = new WP_Automatic_Updater;
if ( $check_vcs->is_vcs_checkout( WP_CONTENT_DIR ) ) {
	return;
}
```

So I think there must be a better way. A way that could be found as part of that core ticket.

**Comment by obenland** [comment]
Update-core related changes were not approved for merge, closing.
