### ISSUE TITLE
Add warning for the core redirect

### ISSUE THREAD

**Issue by swissspidy** [obenland/shiny-updates#277]
We probably can't get around the automatic redirect for now, so we should at least show a warning.

Example (shows after core update is initiated):

<img width="578" alt="screen shot 2016-06-11 at 12 20 35" src="https://cloud.githubusercontent.com/assets/841956/15984537/336cc004-2fcf-11e6-8954-4f4043c6fd6f.png">

Exact wording TBD

**Comment by obenland** [comment]
Update-core related changes were not approved for merge, closing.
