### ISSUE TITLE
Sync theme update status between card and modal

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#280]
It's possible to click Update on the theme card and in the modal at the same time.

![theme-sync](https://cloud.githubusercontent.com/assets/617637/16015280/43cbb9ec-3195-11e6-9ef0-c16b565369fb.gif)
![theme-sync2](https://cloud.githubusercontent.com/assets/617637/16015283/44e86d48-3195-11e6-8af4-f3f7457fdaf6.gif)
![theme-sync3](https://cloud.githubusercontent.com/assets/617637/16015286/45da24b2-3195-11e6-86d3-d4f02ea0e38f.gif)

**Comment by swissspidy** [comment]
@obenland You're more familiar with that screen — got time to look at it?

**Comment by obenland** [comment]
Sure

**Comment by obenland** [comment]
Fixed in https://github.com/swissspidy/develop.wordpress/commit/d488b49551a25259cd8b2098c8e97f38b82ecda9.
