### ISSUE TITLE
Console log update messages come in clumps

### ISSUE THREAD

**Issue by afragen** [obenland/shiny-updates#282]
Currently, when that AJAX update happens viewing the console log shows the update messages as follows.

```
[Log] Enabling Maintenance mode…
[Log] Downloading update from https://bitbucket.org/afragen/test-bitbucket-child/get/0.4.0.zip…
[Log] Unpacking the update…
[Log] Installing the latest version…
[Log] Removing the old version of the theme…
[Log] Theme updated successfully.
[Log] Disabling Maintenance mode…
```

When watching this in real time the whole group is written at the same time instead of as they happen.

Is there any way to have this write out as it happens instead of as a group at the end of the process?

The reason why is so that the user can get a sense of where in the process they are.

**Comment by swissspidy** [comment]
Unfortunately it's not that simple to implement this and not of much use for the majority of users.

With simple AJAX calls (request – response) this is not possible. We could do polling using something like the heartbeat API in core, where you ping the server every X seconds to check the progress. But updates usually happen too fast (< 1 min) for this to be reliable and it would be bad for server health to fire so many requests. Also, it would require lots of changes in the core upgrader classes.

Web sockets could be an option, enabling us to show real update progress, but we don't really need that either.

Maybe some day 🙂

**Comment by afragen** [comment]
No problem. Just figured I'd ask. 😄
