### ISSUE TITLE
Trigger event handler when updating theme

### ISSUE THREAD

**Issue by DavidAnderson684** [obenland/shiny-updates#283]
Hi,

Sorry to post this here as well as in Trac a couple of days ago... but I'm a bit nervous about the line "From this point on, no more commits for any new enhancements or feature requests in this release cycle" in https://make.wordpress.org/core/version-4-6-project-schedule/ ... though, perhaps this should be considered a bugfix, since it breaks existing functionality for my plugin (different versions of which have 800,000 active installs).

Here's the issue - I need an event to be triggered so that I can hook into the flow:
https://core.trac.wordpress.org/ticket/37216

Many thanks,
David

**Comment by swissspidy** [comment]
Closing as this has been fixed in core.
