### ISSUE TITLE
Shiny plugin uploads

### ISSUE THREAD

**Issue by j-falk** [obenland/shiny-updates#32]
*I saw the discussion around drag/drop plugin/theme uploader on https://github.com/obenland/shiny-updates/issues/13 and thought I would create a separate issue specific to that.*

So if one purpose of this feature plugin is:
>As a WordPress administrator I want to easily upload and install plugins from my computer so that I can add awesome functionality to my WordPress.

So the existing process looks like:
![untitled gif 1](https://cloud.githubusercontent.com/assets/1665833/12070370/48c343f8-b070-11e5-947d-cd2e2878dacf.gif)

This is a for example a much different uploading experience than what you today have in the media library which is really great, see this example:
![untitled gif](https://cloud.githubusercontent.com/assets/1665833/12070376/daddfdb4-b070-11e5-85d5-36db8130aee6.gif)

So I think this would be a great improvement to enable:
* Drag/drop upload/install, would simplify upload/install and also unify the experience with how it works in the media library. Being able to do this from plugins-install.php and maybe even plugins.php would be a great improvement.
* Bulk upload/install, would greatly simplify when you want to add multiple plugins which I think is quite typical when setting up a new site, you might have some plugins you always install on every site you create, or when you use a plugin who utilize a extensions approach eg when using WooCommerce it probably isn't too uncommon that you want to add multiple extensions at once.
be great when you need to a

Also another related issue that came up in the comments on the 4.5 wishlist post (https://make.wordpress.org/core/2015/12/30/wordpress-4-5-whats-on-your-wishlist/) was the possiblity to replace an existing plugin instead of failing as it does now:
![untitled gif 1](https://cloud.githubusercontent.com/assets/1665833/12070435/ba5cda34-b074-11e5-869c-722d463a6f87.gif)

It's something I've experienced myself and I think a better management of this would be a great improvement. Here's a link to an existing trac ticket, https://core.trac.wordpress.org/ticket/9757.

Obviously such a improved workflow would also be very beneficial for themes, I could even see bulk uploads as useful on a single install eg. if you upload a theme with a child theme (even if that probably is a bit more for advanced users).

**Comment by paaljoachim** [comment]
Hey j-falk. Good work with showing existing and a possible better approach to uploading plugins as well as showing the existing failed upload approach to a plugin that already exists in the installed plugin screen!

I like the easy bulk upload screen. As it also creates a more unifying experience using a similar approach as the Media Library (as you mention). Transfering the process also to other areas seems very natural as well. 

Replacing a plugin or theme: Should be so that one just receives a message saying overwrite existing plugin/theme. Clicking yes overwrites it. Similar to overwriting a file.

**Comment by Ipstenu** [comment]
FYI - https://core.trac.wordpress.org/ticket/35429 is there now to bring parity to themes.

**Comment by swissspidy** [comment]
I'm confident that this core ticket will be resolved early in the 4.6 cycle, so it doesn't need to be addressed by Shiny Updates.

**Comment by swissspidy** [comment]
Closing this in favour of the core trac ticket. Shiny plugin uploads is out of scope for _Shiny Updates_.
