### ISSUE TITLE
Showing plugins in an infinite scroll view?

### ISSUE THREAD

**Issue by paaljoachim** [obenland/shiny-updates#33]
The scenario.
I go to my favorites and have 8 pages worth of favorite plugins.
Having a page open as a masonry instead of having to click the next page on the bottom I could scroll the page rapidly click the install button of a plugin and move on to the next plugin click it and move on again. Having the "quick update" procedure also with a new plugin install as j-falk mentioned in the other thread. (Meaning the spinner, the word being installed, installed just above the plugin. Keeping it on the same page.)

**Comment by MichaelArestad** [comment]
When you say masonry, can you elaborate? I don't follow. (screenshots help as well)

**Comment by paaljoachim** [comment]
Sorry about that - Masonry is the wrong word. I am looking for word infinite scroll.
Going to install a plugin selecting Get Favorites. I have 8 pages of favorites.
There are 30 plugins listed on each screen. 
As there is a top and a bottom. Scroll to the bottom and it has an arrow to go the previous/next page. But with infinite scroll as I get close to the bottom more plugins show up creating an infinite list of the plugins I have in my favorites screen. I could scroll and scroll and click the plugins I want to have installed without having to go to previous or next page.

**Comment by swissspidy** [comment]
Infinite scroll is easier said than done. The list tables in WordPress currently do not allow for this easily. You need some Ajax functionality for pagination and to reflect any changes to items.

And if we're gonna implement infinite scroll, it would definitely not be just for plugins, but for all list tables. This is, of course, out of scope for shiny updates.

I recommend following the relevant core ticket for this: https://core.trac.wordpress.org/ticket/28050

**Comment by paaljoachim** [comment]
What about screen options to select how many plugins are visible on each page? Is that easier to implement? Thanks for the trac ticket link!

**Comment by swissspidy** [comment]
Isn't there already a screen option for that?

**Comment by paaljoachim** [comment]
Installed Plugins have Screen Options and Help:

![screen shot 2016-04-30 at 00 00 34](https://cloud.githubusercontent.com/assets/5323259/14930753/b458dd68-0e66-11e6-9437-c887030653b1.png)


Adding a new plugin has a help section:

![screen shot 2016-04-30 at 00 01 00](https://cloud.githubusercontent.com/assets/5323259/14930765/c47cfd0a-0e66-11e6-8548-6e9b4afab46f.png)

**Comment by swissspidy** [comment]
@paaljoachim Sorry, yeah, gotcha now. I was thinking of the installed plugins screen, not "Add New Plugin".

That's indeed another topic. I know there were some screen options on that page before, but they were removed (see https://core.trac.wordpress.org/ticket/28803).

It seems the number of plugins per page can be filtered via `install_plugins_table_api_args_$tab`, in case you are looking for a quick solution.

Pretty sure there was a ticket about not adding a "plugins per page" option to that screen, but I can't find it right now.

Infinite scroll is still something that would make sense when everything is being done via JavaScript, just like on the "Add New Theme" page.

**Comment by swissspidy** [comment]
Closing as this is out of scope for the shiny updates v2 initiative. This should be addressed in a core ticket.

**Comment by paaljoachim** [comment]
Alrighty....I am just letting it go.
