### ISSUE TITLE
plugins.php - Cleaner list view with plugin icon, possibility to enable auto-updates and more

### ISSUE THREAD

**Issue by j-falk** [obenland/shiny-updates#34]
*I am not sure this would be considered as something shiny, maybe adding the UI possibility to enable/disable auto-updates could be considered that, but definitely think it would greatly improve the plugin experience so created this issue and maybe it can at least help the discussion of what the exact purpose of this feature plugin is.*

So I think the existing list of installed plugins feels quite cluttered, is quite text heavy and do not include the plugin icons that is being used on the card design when installing .org plugins:
![plugins shiny updates wordpress](https://cloud.githubusercontent.com/assets/1665833/12071707/0e43d612-b0ba-11e5-8cd1-18ef26bc8131.png)

Inspiration of how this could be improved can be found in multiple places, one obvious example is the Calypso interface which is very clean in comparison since eg. not showing description, version, author, edit and delete which is available when clicking on a plugin:
![plugins wp konsulterna wordpress com - 1](https://cloud.githubusercontent.com/assets/1665833/12071670/c893b094-b0b7-11e5-8d38-c3b15a17731f.png)

Another inspiration of how plugin icons could look in the standard WP list view could come from the list view in the media library who also only show actions like Edit, Delete and View on mouse over which makes the screen a bit cleaner:
![media library shiny updates wordpress](https://cloud.githubusercontent.com/assets/1665833/12071677/53f28a34-b0b8-11e5-92b6-e3adc1ead2ea.png)

So here is what I would suggest:
* Include plugin icons, this would better unify the experience with the existing installation process of .org plugins and give a better distinction between installed plugins.
* Remove/hide information as description, version, author, edit and delete to make it a cleaner list
* Add the possibility to enable/disable auto-updates for plugins
* ‘Last Updated’ timestamp and 2 year since last update notice, this was suggested in the comments of https://make.wordpress.org/core/2015/12/30/wordpress-4-5-whats-on-your-wishlist/ and I think that could help the user make a informed decision as to whether the plugin needs to be replaced by an alternative or not.

**Comment by paaljoachim** [comment]
It is awesome that your bringing up this issue!
I have also lately begun comparing the media library grid view and line view to something we could also have in the installed plugins screen.

I just made a quick rough installed plugin wireframe.

![installed-plugins](https://cloud.githubusercontent.com/assets/5323259/12091457/931df96e-b2f7-11e5-8799-163efe803fbb.jpg)

It would be great to have a good visible icon, good size title limited description of the plugin (as I am thinking it would be nice to have a sentence or two in there). Last updated with a text in red if it has gone over 2 years since last update, and a autoupdate feature.

**Comment by adamsilverstein** [comment]
great suggestions and discussion @j-falk, thanks. I like the idea of adding the icons and also taking inspiration from the Calypso design. I like the concept of active/inactive as a toggle verses a button as well.

**Comment by MichaelArestad** [comment]
Will take a stab at this tomorrow.

**Comment by swissspidy** [comment]
See https://core.trac.wordpress.org/ticket/30186 for the relevant trac ticket.

Shiny updates was mentioned there a couple of times. Unfortunately there hasn't been any update for months and it seems like a big overhaul might be out of scope for 4.6.

Maybe we could do a smaller overhaul by adding plugin icons and adding / hiding some data.

**Comment by obenland** [comment]
Yes, I think this is slightly out of scope for Shiny Updates v2.

It's something that will likely be looked at once the new plugin directory is live though!
