### ISSUE TITLE
Find plugins search box in dashboard?

### ISSUE THREAD

**Issue by paaljoachim** [obenland/shiny-updates#36]
Another feature the plugin Cleaner Plugin Installer has is a search box in the Dashboard.

Adding a search in the At a Glanze Dashboard widget looks interesting and am including this here as something to think about.

![screen shot 2016-01-04 at 3 07 42 pm](https://cloud.githubusercontent.com/assets/5323259/12091150/0ce07a0e-b2f5-11e5-83ee-879d72d05b5a.png)

**Comment by obenland** [comment]
Is this really something that belongs in the dashboard though? I think keeping this in a plugin for now would make sense.

**Comment by paaljoachim** [comment]
Agreed.
