### ISSUE TITLE
Shiny Updates Icon

### ISSUE THREAD

**Issue by mapk** [obenland/shiny-updates#46]
I'm working on some ideas for the Shiny Updates icon. Take a look and leave feedback. :)

**Version 2**
Background gradient indicating a blue update color rising to a green success color. Using the simple WP update icon with minor tweaks.
![icon_256x256 v2](https://cloud.githubusercontent.com/assets/617986/12280535/89888d22-b943-11e5-83f9-48aa0891b499.png)

**Version 2b** - color variation
![icon_256x256 v2b](https://cloud.githubusercontent.com/assets/617986/12280551/99d33484-b943-11e5-805d-620fd6df34b7.png)

**Version 3**
A subtle allusion to an 'S' for 'Shiny Updates' in the middle of the update icon.
![icon_256x256 v3](https://cloud.githubusercontent.com/assets/617986/12280554/a32cf56a-b943-11e5-942f-e4f72272a816.png)

**Comment by obenland** [comment]
❤️  Version 2

**Comment by mapk** [comment]
Based off that feedback :) I created the assets and zipped them up. Here they are.
[assets.zip](https://github.com/obenland/shiny-updates/files/88236/assets.zip)

If we needed these tonight, this should do it. I figure we can revise further if desired later on.

**Comment by obenland** [comment]
Committed: https://plugins.trac.wordpress.org/changeset/1327634

What do you think about putting the loading icon to the right and either replacing or dropping the plugin name in the banner? https://wordpress.org/plugins/shiny-updates/
This has the lowest of all priorities btw.

**Comment by mapk** [comment]
Here's the new banner without the text.
![banner_772x250](https://cloud.githubusercontent.com/assets/617986/12301524/541f19a2-b9d5-11e5-98e5-0bd3d5d00a45.png)
![banner_772x250 2x](https://cloud.githubusercontent.com/assets/617986/12301525/542fd544-b9d5-11e5-9ca7-f9d198a8dcd8.png)

**Comment by obenland** [comment]
Thank you!

Fixed in http://plugins.trac.wordpress.org/changeset/1327674
