### ISSUE TITLE
Bulk actions on installed plugins

### ISSUE THREAD

**Issue by mapk** [obenland/shiny-updates#51]
A lot of the user testing revealed that the dropdown for the bulk actions was often missed, or not used as bulk functionality. In addition, the "Apply" button would also be clicked without selecting any plugins. 

Maybe we can follow the advancements of .COM and pull these actions out of the dropdown to display them in the table header. When there are no plugins selected, the buttons remain disabled. But when a plugin is selected, then they become clickable.

Nothing selected
![bulkactions-noneselected](https://cloud.githubusercontent.com/assets/617986/12309591/5ca7de44-ba00-11e5-8b06-71ebbedea232.png)

3 Plugins selected
![bulkactions](https://cloud.githubusercontent.com/assets/617986/12309697/fcb0a952-ba00-11e5-835f-6ea7fa88efa8.png)

**Comment by obenland** [comment]
This should probably be proposed outside of Shiny Updates. There are a ton of list tables around the admin that use dropdowns for bulk actions. Smells like it's own feature plugin to me.

**Comment by MichaelArestad** [comment]
Yeah. This definitely outside shiny updates realm. It's probably its own feature plugin TBH. Closing this for now.

**Comment by MichaelArestad** [comment]
It's also worth noting it deserves its own plugin because that kind of interface is difficult to work with in translations and on mobile and might be slow-moving/difficult. We should still do it, but Shiny Updates shouldn't hinge on it.
