### ISSUE TITLE
Match colors between different notifications

### ISSUE THREAD

**Issue by mapk** [obenland/shiny-updates#52]
The notification circle next to the "Plugins" in the sidebar is **blue** while the actual plugin that it's referring to is highlighted in **orange**. When on the list page, active plugins have the **blue** bar, so the circular notification in the sidebar seems to relate visually to the active plugins and not with the plugin that needs the update.

![screen shot 2016-01-14 at 12 04 07 pm](https://cloud.githubusercontent.com/assets/617986/12336114/77c89e54-bab7-11e5-9bd6-1c8a8b437e5b.png)

**Comment by obenland** [comment]
With the notification in the description cell, I don't think we need to highlight the entire row anymore. What do you think of this? We have the orange arrows on yellow ground over at themes already. I think it works quite well.

![screen shot 2016-01-15 at 8 42 10 am](https://cloud.githubusercontent.com/assets/1398304/12358970/e14d7bb2-bb64-11e5-8862-22c38f7bde93.png)
![screen shot 2016-01-15 at 8 42 25 am](https://cloud.githubusercontent.com/assets/1398304/12358971/e14f01bc-bb64-11e5-9970-6e1791cab7ed.png)
![screen shot 2016-01-15 at 8 44 23 am](https://cloud.githubusercontent.com/assets/1398304/12358969/e14d3d78-bb64-11e5-86be-9067bea94920.png)
![screen shot 2016-01-15 at 8 44 59 am](https://cloud.githubusercontent.com/assets/1398304/12358968/e14c1862-bb64-11e5-9f17-24f5229715d0.png)
![screen shot 2016-01-15 at 8 45 32 am](https://cloud.githubusercontent.com/assets/1398304/12358972/e15086d6-bb64-11e5-85b4-4d6083fc817c.png)

**Comment by mapk** [comment]
I like it. I'm totally in favor of the notifications having a colored background. It helps them stand out and gives a well accepted color association to what's going on.

Let's do it.  Although I think this relates more to this issue where we've been exploring these things: https://github.com/obenland/shiny-updates/issues/7

This issue is about getting the color of the circular notification in the sidebar to match the color of the notification it's relating to.

**Comment by mapk** [comment]
One thing to note as well. I'm not sold on the 'X' as being the icon related to the 'failed' notification, especially when we use the 'x' elsewhere to denote 'close' like on the Theme notification you showed.

In our Dashicons set we have that 'warning' icon which I think would work better: https://developer.wordpress.org/resource/dashicons/#warning

**Comment by obenland** [comment]
> This issue is about getting the color of the circular notification in the sidebar to match the color of the notification it's relating to.

I'm not sure that should be part of this plugin. It's part of the general admin color scheme. That color will be different with different color schemes.

**Comment by mapk** [comment]
Ah got it. Thanks for clarifying. We can probably close this one then, yea?

**Comment by obenland** [comment]
Sure :)
