### ISSUE TITLE
Update Themes from Card View

### ISSUE THREAD

**Issue by mapk** [obenland/shiny-updates#54]
A common request is to be able to update the theme from the card view screen without having to click the theme and then update from the modal.

Here is a proposed solution to the current update notification. We can use that space to add a link to update.

![update themes v1b](https://cloud.githubusercontent.com/assets/617986/12437098/c9d8bb54-becf-11e5-9cf2-33bca1cfac37.png)

I'm still exploring some alternate solutions.

**Comment by mapk** [comment]
I'm still exploring some alternate solutions.

**Comment by mapk** [comment]
I also explored an idea more inline with our current update design for plugins. 

![update themes v2](https://cloud.githubusercontent.com/assets/617986/12456398/7215c724-bf54-11e5-916c-aeea40a22355.png)

I don't think it works as well in relation to the card view layout though.

**Comment by mapk** [comment]
If we want to mimic the dark grey bar along the bottom of the Theme wherein the CTA exists as a button, this might be a possible solution.

![update themes v1](https://cloud.githubusercontent.com/assets/617986/12456707/e2c44c06-bf55-11e5-8403-25f221176c9c.png)

**Comment by obenland** [comment]
I like the consistency with plugins and how it's displayed in the theme modal in version 2.
What do you think of "New version available. [link]Update now[/link]" to continue keeping it in line with plugins?

**Comment by mapk** [comment]
Yes, I wasn't sure if that's the direction we were going yet with plugins. If we're keeping it as a link with plugins, we should keep it as a link here too. I would still right justify the link away from the msg.

**Comment by obenland** [comment]
How should we handle error messages there? We don't have enough room to display most of them

**Comment by mapk** [comment]
I would imagine the error msg would replace the update msg. The colored bar would assume the same styles as the error msg on the plugins in page.  It should be flexible (not a fixed height) so that it can grow with the error msg.

@obenland Do you have some examples of the error msgs? I can mess around to see if this solution would be appropriate.

**Comment by obenland** [comment]
`Update Failed: Theme update failed.`
`Update Failed: Update package not available.`
`Update Failed: The theme is at the latest version.`
`Update Failed: You do not have sufficient permissions to update themes on this site.`

**Comment by mapk** [comment]
Staying inline with the other notifications, I imagine the error notification would looks something like this. Yes/No?
![error themes v3](https://cloud.githubusercontent.com/assets/617986/12657454/3ed8493a-c5b8-11e5-8400-0942bd9f6e16.png)

**Comment by mapk** [comment]
Due to the user testing feedback, I wonder if something like this would be better.

![update themes v1b](https://cloud.githubusercontent.com/assets/617986/12861862/4a6edea8-cc1b-11e5-9669-32fd88fb3a14.png)

**Comment by swissspidy** [comment]
Any update on this? How does it currently look like and what do testers say?

**Comment by obenland** [comment]
Oh, this is done, not sure why the issue is still open. 563ff7cf87c97fd18f0d16d239aded0b885e5180 and 8cc2918280e95f7bac788bee1ea60412a058da85 added support for that. [The visual records](https://make.wordpress.org/flow/2016/05/02/shiny-update-visual-records/) contain a record of how it looks now.
