### ISSUE TITLE
Add activate action button

### ISSUE THREAD

**Issue by Zodiac1978** [obenland/shiny-updates#55]
If I install a new plugin I get a grayed out button "Installed", but no button to activate the plugin. I have to switch to "Installed plugins", look/search for the plugin and activate it. Why not adding a button/link "Activate" additional or instead of the "Installed"?

![bildschirmfoto 2016-01-22 um 16 08 21](https://cloud.githubusercontent.com/assets/870475/12514259/bd8fb582-c122-11e5-9dbe-d7298b31f969.png)

Great feature plugin so far! Really like it :)

**Comment by mapk** [comment]
Due to some current technical limitations (we don't have a way to reliably deal with fataling plugins through AJAX) we chose not to incorporate activations on this page for now.

I'll close this issue for now, but if you have more questions, just ask. :)
