### ISSUE TITLE
Feedback on update progress

### ISSUE THREAD

**Issue by afragen** [obenland/shiny-updates#6]
I realize that the goal is to use shiny updates for everything and this is great, but I just want to ensure that there will be some method/setting to show the update progress. This information is invaluable for debugging and I'd hate for it to go away.

Perhaps something hooked to `WP_DEBUG`?

**Comment by obenland** [comment]
Can you elaborate? How does the information that the Installer currently displays help you debug?
What kind of additional debug information would you suggest to be displayed in shiny processes?

**Comment by afragen** [comment]
It shows the URL for the download link. It describes the steps along the path: unpacking, installing, removing old plugin, etc. When and if an error occurs it describes that error.

If the download link and any errors were reported that would be enough. And they could even overwrite each other so that first you could see the download link and if a error occurred the error would be displayed, if success, the download link would be overwritten with an empty string. Or something, I still want the keep the process clean.

**Comment by adamsilverstein** [comment]
Good suggestion.  For user notifications, we are working on a new way to do these.

For debugging I like the idea of some additional logging for error conditions if WP_DEBUG is enabled.  

Would you like to work on a pull request @afragen?

**Comment by afragen** [comment]
Sure. What style are you interested in?

1. Only if WP_DEBUG is true
2. Inline feedback

**Comment by afragen** [comment]
Well this is at least a great reason to start learning JavaScript.
