### ISSUE TITLE
Installation requires navigation to access features

### ISSUE THREAD

**Issue by Clorith** [obenland/shiny-updates#64]
I brought this up the last time around as well, I love the concept of shiny updates, but in the shoes of a non-power user I have now clicked "Install", and have no idea where to go from that.

At least half the plugins add menu items and settings pages that require interaction for them to be usable.

So if I click install, I would have to have already "left" to do something else in the dashboard to discover the newly added menu item for example.

Perhaps a shiny updates hook to push a notification with the installation success that authors can utilize would help to point the user in the right direction, or maybe a way of fetching the left hand navigation area of the admin when the event queue is cleared ? (just some ideas to get the ball rolling on this, as I want to see this become a thing!)

**Comment by obenland** [comment]
Wouldn't the plugin have to be activated in order for those setting pages and menu items to show up?

**Comment by Moonomo** [comment]
Should not the install process done both installation and activation? Why we need to activate it taking yet another action? 

I'm not sure how many users would install it, and wont want it to be activated immediately.

**Comment by obenland** [comment]
> Why we need to activate it taking yet another action?

There are a lot of plugins that will redirect a user to its settings page to do an initial set up. Having that happen on the next page load, for example when a user wants to go write a post after installing/activating a plugin, can be jarring and is not a pleasant experience. We can also not make sure that the plugin will not trigger a fatal error upon activation. Lastly, the goal of Shiny Updates v2 is to get rid of The Bleak Screen of Sadness, which does not occur for activations. For these reasons we decided to continue to require a page reload for activating a plugin or theme.

**Comment by Moonomo** [comment]
Thanks for the explanation. By saying "yet another action" I wanted to point the "the button for activation". 

Currently installation, and activation requires two different button press from User, and done individually. However, It is possible to press one button which will trigger and complete installation. and soon after automatically trigger activation- the process could then finish with a page reload. WP-CLI does allow this with one single command. If I understood correctly It's a matter of UI to allow one-click-installation-and-activation from the frontend.

From the discussion  on [Facebook AWP Group](https://www.facebook.com/groups/advancedwp/permalink/1142557625806450/) it's evident that- not all cases demands one-click-installation-and-activation. So placing one button to replace current system (== one button to install, and another button to activate) isn't a good option.

it's possible to introduce a checkbox (here's [the mock-up](https://www.dropbox.com/s/k52jy2cr2ry5ox2/option-for-one-alick-installation-and-activation.jpg?dl=0))- enabling which could trigger both installation-and-activation- I think it could improve the overall UX, and could solve this reported issue.

Would love to know your opinions and/or any pros/cons of the idea. Thank you.

**Comment by obenland** [comment]
Right, WP-CLI doesn't have to worry about redirects etc.
It's an interesting UX question, that's for sure. Currently you have to go back to the installed plugins screen to activate them, it's probably not as convenient as doing it all from plugin-install.

Providing activation options there comes at a cost though. Both, triggering a page-refresh after installation to activate, and adding a checkbox, would prevent users from installing more than one plugin at a time and queueing these requests. As you mentioned too, there are valid use cases where you wouldn't want to have it activated after installation (thinking of multisite, where a plugin can be site-specific or network-wide). And adding a checkbox also comes at an expense in terms of UI.

Frankly I'm not sure what the best option is here. The current way feels like the least offensive, giving us the most flexibility.

**Comment by swissspidy** [comment]
See also https://core.trac.wordpress.org/ticket/31002

There was some discussion about doing install-and-activate in one go before, and it wasn't implemented. But giving the option to activate the plugin after it was installed seems like a good compromise.

**Comment by obenland** [comment]
> But giving the option to activate the plugin after it was installed seems like a good compromise.
Two things to be aware of here are having multiple installations in a queue (that currently block navigating away from the page), and what replacing actions in the same element means from a UX perspective.

**Comment by swissspidy** [comment]
@obenland Agree! Look at it without Shiny Updates though: The page reloads after install anyway and there might be another plugin in the list that is already installed too. In that case, having an "Activate" button instead of just "Installed", is absolutely legit.

**Comment by obenland** [comment]
@mapk @MichaelArestad Any opinion on swaping actions in a button and changing its functionality as described above?

**Comment by mapk** [comment]
I mocked this idea up so that we have something to review. I'm not opposed to swapping out the action of a button, but my concern is if the button still remains the same color/style, it could be completely overlooked. The mockup shows two different flows; one with just a new button for activation, and the other with a disabled button similarly to how we do it now but with a message as well to encourage the activation.

![activate-button](https://cloud.githubusercontent.com/assets/617986/14960802/4cbb8cdc-104b-11e6-9114-5a099f2d2782.png)

Any thoughts? I'm still uncertain about the technical adventures this might include.

**Comment by Moonomo** [comment]
I like the second mock-up (the right side)- it's clear action-wise, and the disabled button helps avoid any confusions.

**Comment by mapk** [comment]
As an alternative option, if technical limitations prevent this from being effective and usable, maybe we just offer up a reminder to activate with a link to the plugins page?

**Comment by Moonomo** [comment]
Two different scenario: 

1) Plugin is already installed. I just have to activate. Seems the first mock-up (left-side) is good fit in this case.

2) Plugin is not yet installed. I've to install and activate. The second mock-up (right-side) does a good job indicating the flow.

Picking just the second-flow could work.for both cases though.

**Comment by obenland** [comment]
I think the left mockup looks a lot cleaner. Changing the priority of the button makes sense too. We should think about delaying that until the install/update queue is empty though.

I would love to hear more UX opinions before we move forward with this

**Comment by afragen** [comment]
@obenland I agree re: left side being cleaner. Confusion shouldn't really occur as the button says Activate, not Install. I hope we're all smart enough to know that Activate wouldn't ever show for a non-installed plugin. 😉 

The next question. Currently installed plugins show in this search with a button labeled **Installed*. What will the _presumed_, disabled button text be now? **Installed and Activated**?

**Comment by swissspidy** [comment]
> The next question. Currently installed plugins show in this search with a button labeled Installed. What will the presumed, disabled button text be now? Installed and Activated?

Just *Activated* I guess. Too long otherwise imho.

**Comment by obenland** [comment]
Yeah, I don't think we need to be overly specific there

**Comment by Moonomo** [comment]
It might not that simple for anew user- who isn't familiar with WordPress. The second flow clarify things better for 'em- may be a bit too much for power users though.

**Comment by swissspidy** [comment]
re: the flow, I'd love to have something like "Installing…" -> "Installed" -> (fade out) -> "Activate".

**Comment by Moonomo** [comment]
> "Installing…" -> "Installed" -> (fade out) -> "Activate".

Looks good. May be "please activate" isn't necessary, following also could work: 

"Install now" -> "Installing…" -> "Installed" -> (add the button) -> "Activate".

**Comment by adamsilverstein** [comment]
This is a great idea. Watching the user test its striking how installing and activating a plugin now has a broken flow. I like the left hand simpler mocks as well.

One flow left out here is the case of a non-active plugin with an update available. In this case would we show just the update button, or both update and activate buttons? and would activate still be 'primary'?

**Comment by ocean90** [comment]
I agree that "please activate" isn't necessary.

**Comment by mapk** [comment]
> re: the flow, I'd love to have something like "Installing…" -> "Installed" -> (fade out) -> "Activate".

Here's another mockup to visualize this flow. (sans the animation)

![install-activate-v2](https://cloud.githubusercontent.com/assets/617986/15197710/cc24b83e-1787-11e6-8a39-cf48d8227be0.png)

**Comment by hugobaeta** [comment]
I think this last proposal by @mapk makes the most sense. I have a concern, when installing multiple plugins (probably a rare action), that the screen would be filled with primary action buttons. An alternative would be to replace the button with a text link to activate, which would also provide room for a "Network Activate" when in multisite.

**Comment by adamsilverstein** [comment]
@hugobaeta I like this last suggestion - a text `Activate` link. I started work on this to explore in https://github.com/obenland/shiny-updates/tree/activation-flow - so far I am adding the activation link on initial page load when a plugin is installed, inactive, and the user has activation caps. Next step will be adding it dynamically after a shiny install.

Looks like this: ![](http://cl.ly/1Z253B471w2E/Add_Plugins__WordPress_Dev__WordPress_2016-05-13_10-32-49.jpg)

**Comment by swissspidy** [comment]
Would be great if we could to some user tests with the three variations:

* primary activation button
* secondary activation button
* activation link

In favour of an actual button though, as the link seems too easy to miss.

**Comment by swissspidy** [comment]
See #120 for the current state of the plugin activation flow, including screenshots and gifs.

Right now I like the 'Activate' button better as the text link is just too unobtrusive.
