### ISSUE TITLE
Item counts use different placement and styling throughout

### ISSUE THREAD

**Issue by mapk** [obenland/shiny-updates#68]
The Plugins item counts are located and styled differently than the Themes item count.

Plugins
![plugins-item-count](https://cloud.githubusercontent.com/assets/617986/12796761/4e8131b4-ca75-11e5-85d4-2bd8de4d6c35.png)

Themes
![theme-item-count](https://cloud.githubusercontent.com/assets/617986/12796764/52a62d1c-ca75-11e5-952b-ac1f94d66878.png)

Can we make them the same?

**Comment by mapk** [comment]
Even going beyond this, should we make the search boxes consistent too?

**Comment by afercia** [comment]
About the search field, there's a ticket for that :)

Uniform Search Form Display/Experience
https://core.trac.wordpress.org/ticket/31818

**Comment by obenland** [comment]
Yeah, I don't think this is something for this plugin to worry about. I'm not even sure this is something that needs fixing at all. Plugins and Themes UIs are inherently different, picking out one part of it might not be too helpful. Also keep in mind that the item count in the plugins screen will convert into a pagination once there are more plugins available than the screen option allows to be displayed.
