### ISSUE TITLE
#a11y Add 'version' in aria-label for plug-in install

### ISSUE THREAD

**Issue by joedolson** [obenland/shiny-updates#70]
When installing a new plug-in, the aria-label is "{plugin name} {version number}". Suggest changing to "{plugin name}, version {version number}" to insert a pause between the plugin and the version number and to clarify what that number represents.

**Comment by obenland** [comment]
Can you point me to where in the code that label is added? I have a hard time finding it.

**Comment by joedolson** [comment]
Hmm. I don't remember; I'll look around.

**Comment by joedolson** [comment]
Looks like this is actually in core `class-wp-plugin-install-list-table.php` line 462.

**Comment by obenland** [comment]
Ah, in a core file. That should probably be fixed in a separate ticket in core, rather than overwritten in this plugin.
