### ISSUE TITLE
#a11y Color contrast on updating icon

### ISSUE THREAD

**Issue by joedolson** [obenland/shiny-updates#71]
When in a passive state (no action or completed), the updating icon is fairly trivial, so the low contrast yellow isn't really significant. However, while an action is taking place, I think it would be valuable for that process icon to change color for better visibility. It's not crucial, since the text also changes, but I feel that it would give greater user confidence.

**Comment by obenland** [comment]
@mapk: Could we reconsider going back to the orange color that updates currently use? It would help with the contrast and I think it would look less bland.

**Comment by mapk** [comment]
Let's use this orange: #F56E28

It's the orange from Hugo's color palette. I tried it in the inspector, and thought it looked good. Definitely brighter.  Let's use that orange for both the left border and the icon.

![screen shot 2016-04-13 at 8 50 33 am](https://cloud.githubusercontent.com/assets/617986/14499897/ced9f560-0154-11e6-81b1-bb9a0aacdc3a.png)
