### ISSUE TITLE
Testing the newest plugin update

### ISSUE THREAD

**Issue by paaljoachim** [obenland/shiny-updates#85]
Installed plugins:
The line update now bar looks nice. After having clicked update now and after the spinner has spun it ends up with a checkmark and the word Updating.... (not updated). 

![screen shot 2016-04-21 at 17 25 40](https://cloud.githubusercontent.com/assets/5323259/14714969/5d4f5b44-07e7-11e6-8c66-f63ade3b53fd.png)

Delete plugin opens up a new screen. Activate/Deactivate the screen jumps to the top.

It would be good to keep things consistent having a spinner for Update, Activate/Deactivate and Delete. 

Add Plugins 
6 Featured plugins. 
Popular has 34 pages with 30 items on the first page. 
Recommended: Based on the plugins I have installed. 

It would be good to have a screen options tab to change how many items are seen on each page. Perhaps a better navigation between pages as well.
Clicking the Installed button to uninstall a plugin.
Search by star rating, downloads etc?

Themes:
Similar light yellow background color behind Update now text link. Updates nicely inline with a spinner that is there for a few seconds. Then a checkmark and the word Updated!

Dashboard -> Updates.
Has the added Automatic Updates section on the bottom of the screen.

Is there anything else I should take a closer look at?

**Comment by obenland** [comment]
Thank you for testing and sharing your feedback @paaljoachim!

> after the spinner has spun it ends up with a checkmark and the word Updating.... (not updated).
That is really odd. I can't reproduce it on my local install. I wonder if anyone else can?

> Delete plugin opens up a new screen.
Can you elaborate on that? It should give you a confirmation alert and then just remove the plugin from the list.

> Activate/Deactivate the screen jumps to the top.
Right, this still works like it used to and will continue to do so.

**Comment by paaljoachim** [comment]
Retesting... the same site through my locale development.
Add new plugin -> Shiny Updates Version 2-20160416.
(I am also deactivating all other plugins.)

Updating plugins is working now. It goes to the word Updated. So whatever hickup I had earlier is now gone.

Delete plugin: Brings up a popup dialog box

![screen shot 2016-04-27 at 00 10 43](https://cloud.githubusercontent.com/assets/5323259/14835868/82100c66-0c0c-11e6-916c-4eba190bb2d4.png)

I hope that this is just a temp solution. It seems more natural that the message would show in the yellow bar. In a similar way that updating takes place. Having a popup dialog box just saying are you sure you want to delete this item brings it out of context. As it does not connect in with the plugin.
Having the words in the yellow bar with red delete text would be better.

It seems the plugin I have earlier tested was an earlier version (weird since I did install from the repo same as I did this time). Anyhow the result is different this time around.

**Comment by obenland** [comment]
> It seems more natural that the message would show in the yellow bar.

There is only a yellow bar if there is an update available, so we don't really have anything to work with on up-to-date plugins.

Deleting a plugin now works like deleting a category or tag, where there is also a AYS message first before proceeding and permanently deleting the item.

**Comment by paaljoachim** [comment]
An inline are you sure you want to delete this plugin? message would associate the specific plugin with the delete message. Perhaps have a message show up right under the red delete text or somewhere else close by the plugin information.

**Comment by paaljoachim** [comment]
Another thought...
Should we group installed plugins by status activated and deactivated and then alphabetical? 
As it would give a quicker view of which plugins are activated and which are not.
One would also be able to easier select a bunch of plugins next to each other and deactivate or activate.

**Comment by obenland** [comment]
Adding a message inline is unfortunately not trivial. Since this is a table we'd have to add a new row and make sure that works for both single and multisite installs. @mapk, what do you think about the way we display the AYS message?

I feel like sorting plugins is not necessarily something that needs to be part of this iteration. The goal is primarily to get rid of the bleak screen of sadness when performing theme/plugin-related actions.

**Comment by mapk** [comment]
I just installed the Shiny Updates plugin on the site wpuxtesting.com and went through the process of deleting a plugin and I didn't get the AYS popup message.  I went through and tried out the Theme's flow and thought it was fine. I think anything inline would be visually missed. This alert box is prolly the best way to go until we create a more customized feel.

**Comment by paaljoachim** [comment]
The thing is that clicking delete text link a box shows up saying Are you sure you want to delete this item? If one has clicked the wrong delete text link the box does not list the name of the plugin or does not show up right by the plugin one can easily accidentally delete the wrong plugin. If the name of the plugin is listed then that will help.

**Comment by mapk** [comment]
Good point, @paaljoachim. It shouldn't be a problem adding the plugin name to the alert box should it, @obenland? 

I realize it doesn't do this in the Themes, but it works because the user is only viewing one theme when getting ready to delete it. In the case of the plugins, it would be good to show the name in the alert box.
