### ISSUE TITLE
Prevent install/update from being terminated mid-way

### ISSUE THREAD

**Issue by jrfnl** [obenland/shiny-updates#92]
As the installs/updates are now being run in the background, users may not always be aware that the process is still running and might click away from the page effectively terminating the install/update halfway and potentially leaving users with broken plugins/themes.

Using [`ignore_user_abort()`](http://php.net/manual/en/function.ignore-user-abort.php) will prevent the install/update from terminating mid-way allowing it to finish normally even if the user has moved away.

The way to implement it normally would look something like this:
```php
// some checks and whatever
ignore_user_abort( true );
//critical code which shouldn't be stopped mid-way
ignore_user_abort( false );
// send feedback to the user and such
```

Then again - maybe this should be fixed in core ?

**Comment by swissspidy** [comment]
I'm pretty sure using `ignore_user_abort()` was once discussed for core.

I think we shouldn't use that function but display a JS confirmation dialog when trying to leave the page, i.e. "Are you sure you wanna leave the page?"

**Comment by ocean90** [comment]
> I'm pretty sure using `ignore_user_abort()` was once discussed for core.

See https://core.trac.wordpress.org/ticket/32652.

**Comment by swissspidy** [comment]
Thanks @ocean90, you're really everywhere it seems! 😄 

In that case, I'd suggest adding a "AYS" dialog as part of this plugin and leave the `ignore_user_abort()` discussion to core.

**Comment by jrfnl** [comment]
> See https://core.trac.wordpress.org/ticket/32652.

Looking through the ticket and related tickets it seems that "people" agree it should be used, but nobody ever took any action. When I have the time, I might have a go at it.

**Comment by swissspidy** [comment]
There's already `wp.updates.beforeunload` in the JS, therefore I'm closing this.

We can continue work on https://core.trac.wordpress.org/ticket/32652
