### ISSUE TITLE
Theme update doesn't update theme details

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#96]
See screencast:

![themes](https://cloud.githubusercontent.com/assets/617637/15161443/85701d5e-16fe-11e6-9af7-4dcb9393dd3d.gif)

**Comment by adamsilverstein** [comment]
Fixed in https://github.com/obenland/shiny-updates/pull/104

Screencast:
![Screencast](http://cl.ly/2q0Q1O2C2L3H/Screen%20Recording%202016-05-15%20at%2006.47%20PM.gif)
