### ISSUE TITLE
Don't use `filter_var()`

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#98]
`filter_var()` is currently used by two functions. WP doesn't use the filter functions because the filter extension can be disabled.

**Comment by obenland** [comment]
What should be used instead?

**Comment by swissspidy** [comment]
Current usage:

```
$plugin = filter_var( wp_unslash( $_POST['plugin'] ), FILTER_SANITIZE_STRING );
```

I assume `$_POST['plugin']` is the plugin's name. In that case I'd use `sanitize_text_field()`.

**Comment by obenland** [comment]
It's the plugin basename, so `hello-dolly/hello-dolly.php`. Yeah, we'd need to test that.

**Comment by swissspidy** [comment]
Ah, I see.

Well, core uses `plugin_basename()` for that, e.g. in `wp-admin/includes/plugin.php`:

```
// Sanitize the plugin filename to a WP_PLUGIN_DIR relative path
$plugin_file = plugin_basename( $plugin_file );
```
