### ISSUE TITLE
Bulk plugin update message doesn't handle plural forms

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#99]
<img width="430" alt="" src="https://cloud.githubusercontent.com/assets/617637/15163022/6e347cf4-1706-11e6-8911-9c416df0b63a.png">

https://github.com/obenland/shiny-updates/blob/6e1a76e3cf5650f2cf96235db961731d4b14dbff/src/class-shiny-updates.php#L90

https://core.trac.wordpress.org/ticket/20491 and https://core.trac.wordpress.org/ticket/22229 would be helpful for this.

**Comment by swissspidy** [comment]
Fixed in 59dade90d84da8c8dc8e764586edfd7705987c72 three days ago.

For now this works fine, but of course we should improve JS i18n stuff in core.
